import {state,uid,activeMessages,findChat,findFolder} from './state.js';
import {$,$$,show,hide,toggle,placeMenu} from './dom.js';
import {renderAll,renderChats,renderFeed,appendMessage,markMessageLocallyGone,unmarkMessageLocallyGone} from './render.js';
import {appear,pending,restore,removeAnimated,DELETE_DELAY} from './animations.js';
import {sendStoreMessage,isChatStoreReady,subscribeMessages,deleteStoreMessageForMe,deleteStoreMessageForAll} from './chatStore.js';

let selectedFile=null;
const sleep=ms=>new Promise(r=>setTimeout(r,ms));

function toast(text){let el=document.getElementById('fireDebugToast');if(!el){el=document.createElement('div');el.id='fireDebugToast';el.style.cssText='position:fixed;left:50%;bottom:22px;transform:translateX(-50%);z-index:99999;background:rgba(10,12,12,.96);color:#fff;border:1px solid rgba(255,255,255,.18);padding:10px 14px;box-shadow:0 12px 40px rgba(0,0,0,.55);font:12px system-ui;max-width:min(520px,calc(100vw - 28px));white-space:pre-wrap;pointer-events:none';document.body.appendChild(el)}el.textContent=text;clearTimeout(el._t);el._t=setTimeout(()=>el.remove(),3000)}
function closeTransient(){hide($('#profileModal'));hide($('#deleteModal'));hide($('#chatCtx'));hide($('#ctx'));hide($('#folderCtx'));hide($('#moreChatCtx'));$('#deleteModal')?.classList.remove('rowDelete','messageDeleteStrict')}

export function bindActions(){
  $('#collapse').onclick=()=>{const app=$('#app');app.classList.toggle('collapsed');$('#collapse').textContent=app.classList.contains('collapsed')?'›':'‹'};
  $('#menu').onclick=()=>$('#app').classList.toggle('mobile');
  $('#membersBtn').onclick=()=>toggle($('#members'));
  $('#closeMembers').onclick=()=>{hide($('#members'));hide($('#profileModal'))};
  $('#contactsBtn')?.addEventListener('click',openContactsPanel);
  $('#newChat').onclick=e=>{e.preventDefault();openCreateChatModal()};
  $('#folderBtn').onclick=e=>{e.preventDefault();openFolderModal()};
  $('#searchBtn').onclick=()=>$('#headerSearch').classList.toggle('show');
  $('#stickerBtn').onclick=()=>placeStickers();
  $('#send').onclick=sendText;
  $('#input').onkeydown=e=>{if(e.key==='Enter'&&!e.shiftKey){e.preventDefault();sendText()}};
  $('#attach').onclick=()=>$('#fileInput').click();
  $('#fileInput').onchange=e=>previewFile(e.target.files?.[0]);
  $('#closeFile').onclick=()=>hide($('#filePreview'));
  $('#confirmFile').onclick=sendFile;
  $('#cancelDelete').onclick=()=>{hide($('#deleteModal'));$('#deleteModal')?.classList.remove('rowDelete','messageDeleteStrict')};
  $('#confirmDelete').onclick=confirmDelete;
  $('#undoDelete').onclick=undoDelete;
  document.addEventListener('click',globalClick,true);
  document.addEventListener('contextmenu',globalContext,true);
  bindSmoothDrag();bindDrop();bindSidebarSearch();renderAll();
}

async function sendText(){const input=$('#input'),text=input.value.trim();if(!text)return;const reply=state.replyTo;state.replyTo=null;input.value='';if(isChatStoreReady()){try{await sendStoreMessage({type:'text',text,replyTo:reply});return}catch(err){toast('Не удалось отправить сообщение:\n'+(err.message||err.code||err))}}appendMessage({id:uid('m'),author:state.user,color:'red',type:'text',text,time:'сейчас',mine:true,reply});updateChatLast(text)}
function updateChatLast(text){const c=findChat(state.activeChat);if(c){c.last=state.user+': '+text;c.time='сейчас';renderChats()}}
function previewFile(file){if(!file)return;selectedFile=file;$('#fileName').textContent=file.name;$('#fileSize').textContent=formatSize(file.size);show($('#filePreview'));$('#fileInput').value=''}
function sendFile(){if(!selectedFile)return;appendMessage({id:uid('m'),author:state.user,color:'red',type:'file',text:'',file:selectedFile.name,size:formatSize(selectedFile.size),time:'сейчас',mine:true});updateChatLast('Файл: '+selectedFile.name);selectedFile=null;hide($('#filePreview'))}
function formatSize(size){const mb=size/1024/1024;return mb<1?Math.ceil(size/1024)+' KB':mb.toFixed(1)+' MB'}

async function globalClick(e){
  if(document.body.classList.contains('drag-live')){e.preventDefault();e.stopPropagation();return}
  const sticker=e.target.closest('[data-sticker]');
  if(sticker){const text=sticker.dataset.sticker;hide($('#stickers'));if(isChatStoreReady()){await sendStoreMessage({type:'sticker',text});return}appendMessage({id:uid('m'),author:state.user,color:'red',type:'sticker',text,time:'сейчас',mine:true});return}
  const chat=e.target.closest('[data-chat-id]');
  if(chat&&!e.target.closest('.ctx')){closeTransient();state.activeChat=chat.dataset.chatId;const c=findChat(state.activeChat);if(c)c.unread=0;renderAll();if(isChatStoreReady())subscribeMessages(state.activeChat);blinkChatSwitch();return}
  const folder=e.target.closest('.folder-item');
  if(folder&&!e.target.closest('[data-chat-id]')){const wrap=folder.closest('[data-folder-id]'),f=wrap&&findFolder(wrap.dataset.folderId);if(f){if(!f.chatIds?.length){f.open=false;renderChats();return}f.open=!f.open;renderChats()}return}
  const ctxAction=e.target.closest('.ctxAction,.reactBtn');if(ctxAction){handleContextAction(ctxAction);return}
  if(!e.target.closest('.float,.hbtn,#stickerBtn,#membersBtn,#newChat,#folderBtn,#contactsBtn'))$$('.ctx').forEach(hide);
}
function globalContext(e){if(e.target.closest('.reactChip'))return;const msg=e.target.closest('[data-msg-id]'),chat=e.target.closest('[data-chat-id]'),folder=e.target.closest('[data-folder-id]');if(msg){e.preventDefault();state.selectedMessageId=msg.dataset.msgId;placeMenu($('#ctx'),e.clientX,e.clientY)}else if(chat){e.preventDefault();state.selectedChatId=chat.dataset.chatId;placeMenu($('#chatCtx'),e.clientX,e.clientY);const c=findChat(state.selectedChatId),pin=$('#chatCtx .chatAction[data-a="pin"]');if(pin&&c)pin.textContent=c.pinned?'📌 Открепить':'📌 Закрепить'}else if(folder){e.preventDefault();state.selectedFolderId=folder.dataset.folderId;placeMenu($('#folderCtx'),e.clientX,e.clientY)}}
function handleContextAction(btn){const a=btn.dataset.a;if(btn.dataset.react)return;if(btn.classList.contains('chatAction'))return handleChatAction(a);if(btn.classList.contains('folderAction'))return handleFolderAction(a);const m=activeMessages().find(x=>x.id===state.selectedMessageId);if(!m)return;if(a==='reply'){state.replyTo=`${m.author}: ${m.text||m.file||'стикер'}`;$('#input').focus()}if(a==='edit'){state.editingId=m.id;$('#input').value=m.text||'';$('#input').focus()}if(a==='forward'){appendMessage({...m,id:uid('m'),time:'сейчас',mine:true,reply:'Переслано'})}if(a==='delete')openDelete('message',m.id);hide($('#ctx'))}
function handleChatAction(a){const c=findChat(state.selectedChatId);if(!c)return;if(a==='pin'){c.pinned=!c.pinned;if(c.pinned){state.chats=state.chats.filter(x=>x.id!==c.id);state.chats.unshift(c)}renderChats()}if(a==='mute'){c.muted=!c.muted;renderChats()}if(a==='delete')openDelete('chat',c.id);hide($('#chatCtx'))}
function handleFolderAction(a){const f=findFolder(state.selectedFolderId);if(!f)return;if(a==='pin'){state.folders=state.folders.filter(x=>x.id!==f.id);state.folders.unshift(f);renderChats()}if(a==='style')openFolderModal(f);if(a==='delete')openDelete('folder',f.id);hide($('#folderCtx'))}

function openDelete(type,id){state.pendingDelete={type,id};const modal=$('#deleteModal'),row=$('.deleteAllRow'),check=$('#deleteForAll');modal.classList.remove('rowDelete','messageDeleteStrict');if(check)check.checked=false;if(row)row.style.display=type==='message'?'flex':'none';hide(modal);if(type==='chat'){modal.classList.add('rowDelete');const r=$(`[data-chat-id="${id}"]`)?.getBoundingClientRect();if(r){modal.style.left=Math.min(window.innerWidth-290,r.right+10)+'px';modal.style.top=Math.max(12,Math.min(window.innerHeight-150,r.top))+'px'}}else if(type==='message'){modal.classList.add('messageDeleteStrict');modal.style.left='';modal.style.top=''}else{modal.style.left='';modal.style.top=''}show(modal)}
function selectorFor(p){return p.type==='message'?`[data-msg-id="${p.id}"]`:p.type==='chat'?`[data-chat-id="${p.id}"]`:`[data-folder-id="${p.id}"]`}
function showUndo(type){$('#undoText').textContent=type==='message'?'Сообщение удалено':type==='chat'?'Чат удаляется':'Папка удаляется';const u=$('#undoToast');u.classList.remove('run');show(u);void u.offsetWidth;u.classList.add('run')}
async function confirmDelete(){const p=state.pendingDelete;if(!p)return;const node=$(selectorFor(p));hide($('#deleteModal'));$('#deleteModal').classList.remove('rowDelete','messageDeleteStrict');if(p.type==='message'&&isChatStoreReady()){const forAll=$('#deleteForAll')?.checked;state.pendingDelete=null;await stageDeleteMessage(p,node,forAll);return}pending(node);showUndo(p.type);clearTimeout(state.undoTimer);state.undoTimer=setTimeout(()=>finalDelete(p,node),p.type==='chat'?500:DELETE_DELAY)}
async function stageDeleteMessage(p,node,forAll){const chatId=state.activeChat;const original=activeMessages().find(x=>x.id===p.id);markMessageLocallyGone(p.id);if(node)removeAnimated(node);await sleep(360);state.messages[chatId]=(state.messages[chatId]||[]).filter(x=>x.id!==p.id);renderFeed();state.pendingDeleteCommit={...p,chatId,forAll,original};showUndo('message');clearTimeout(state.undoTimer);state.undoTimer=setTimeout(async()=>{const commit=state.pendingDeleteCommit;state.pendingDeleteCommit=null;hide($('#undoToast'));if(!commit)return;try{if(commit.forAll)await deleteStoreMessageForAll(commit.id);else await deleteStoreMessageForMe(commit.id)}catch(err){if(commit.original){state.messages[commit.chatId]||=[];state.messages[commit.chatId].push(commit.original)}unmarkMessageLocallyGone(commit.id);renderFeed();toast('Не удалось удалить:\n'+(err.message||err.code||err))}},3000)}
function undoDelete(){clearTimeout(state.undoTimer);state.undoTimer=null;if(state.pendingDeleteCommit?.type==='message'){const c=state.pendingDeleteCommit;state.pendingDeleteCommit=null;if(c.original){state.messages[c.chatId]||=[];if(!state.messages[c.chatId].some(x=>x.id===c.id))state.messages[c.chatId].push(c.original)}unmarkMessageLocallyGone(c.id);renderFeed();hide($('#undoToast'));return}state.pendingDelete=null;$$('.ucmu-delete-pending').forEach(restore);hide($('#undoToast'))}
function finalDelete(p,node){clearTimeout(state.undoTimer);state.undoTimer=null;removeAnimated(node,()=>{if(p.type==='message'){state.messages[state.activeChat]=activeMessages().filter(m=>m.id!==p.id);renderFeed()}if(p.type==='chat'){state.chats=state.chats.filter(c=>c.id!==p.id);state.folders.forEach(f=>f.chatIds=f.chatIds.filter(id=>id!==p.id));delete state.messages[p.id];if(state.activeChat===p.id)state.activeChat=state.chats[0]?.id||null;renderAll()}if(p.type==='folder'){state.folders=state.folders.filter(f=>f.id!==p.id);renderAll()}hide($('#undoToast'));state.pendingDelete=null})}

function makeSlot(from){const el=document.createElement('div');el.className='drag-slot';el.style.height=from.getBoundingClientRect().height+'px';return el}
function makeGhost(from,r){const g=from.cloneNode(true);g.classList.add('drag-ghost');g.style.cssText=`position:fixed!important;z-index:9999!important;pointer-events:none!important;margin:0!important;width:${r.width}px!important;height:${r.height}px!important;left:${r.left}px!important;top:${r.top}px!important;opacity:1!important;`;document.body.appendChild(g);return g}
function listFromPoint(x,y,ghost){ghost.style.display='none';const el=document.elementFromPoint(x,y);ghost.style.display='';return el?.closest?.('.folder-chat-list,#chatList')||el?.closest?.('.side')&&$('#chatList')||null}
function animateFlip(before,list){Array.from(list.querySelectorAll('[data-chat-id],.drag-slot')).forEach(el=>{const b=before.get(el);if(!b)return;const a=el.getBoundingClientRect(),dx=b.left-a.left,dy=b.top-a.top;if(dx||dy)el.animate([{transform:`translate(${dx}px,${dy}px)`},{transform:'translate(0,0)'}],{duration:240,easing:'cubic-bezier(.16,.86,.22,1)'})})}
function placeSlot(drag,x,y){const list=listFromPoint(x,y,drag.ghost)||drag.slot.parentElement;if(!list)return;const before=new Map(Array.from(list.querySelectorAll('[data-chat-id],.drag-slot')).map(el=>[el,el.getBoundingClientRect()]));const items=Array.from(list.querySelectorAll('[data-chat-id]')).filter(el=>el.dataset.chatId!==drag.chatId);let target=null,after=false;for(const item of items){const r=item.getBoundingClientRect();if(y<r.top+r.height/2){target=item;after=false;break}target=item;after=true}if(target)list.insertBefore(drag.slot,after?target.nextSibling:target);else list.appendChild(drag.slot);animateFlip(before,list)}
function flyToSlot(drag,done){const from=drag.ghost.getBoundingClientRect(),to=drag.slot.getBoundingClientRect(),start=performance.now(),dur=230;function step(t){const p=Math.min(1,(t-start)/dur),e=1-Math.pow(1-p,3);drag.ghost.style.left=from.left+(to.left-from.left)*e+'px';drag.ghost.style.top=from.top+(to.top-from.top)*e+'px';if(p<1)requestAnimationFrame(step);else done()}requestAnimationFrame(step)}
function commitDrag(drag){const list=drag.slot.parentElement,ids=Array.from(list.querySelectorAll('[data-chat-id],.drag-slot')).map(el=>el.classList.contains('drag-slot')?drag.chatId:el.dataset.chatId).filter(Boolean);const folderWrap=list.closest('[data-folder-id]');if(folderWrap){const f=findFolder(folderWrap.dataset.folderId);if(f)f.chatIds=[...new Set(ids)];state.folders.forEach(f=>{if(f.id!==folderWrap.dataset.folderId)f.chatIds=(f.chatIds||[]).filter(id=>id!==drag.chatId)});return}const map=new Map(state.chats.map(c=>[c.id,c])),seen=new Set(),next=[];ids.forEach(id=>{if(!seen.has(id)&&map.has(id)){seen.add(id);next.push(map.get(id))}});state.chats.forEach(c=>{if(!seen.has(c.id))next.push(c)});state.chats=next;state.folders.forEach(f=>f.chatIds=(f.chatIds||[]).filter(id=>id!==drag.chatId))}
function bindSmoothDrag(){let drag=null,suppress=false;document.addEventListener('pointerdown',e=>{const item=e.target.closest('[data-chat-id]');if(!item||e.button!==0||e.target.closest('.ctx'))return;const c=findChat(item.dataset.chatId);if(c?.pinned){toast('Закреплённый чат нельзя таскать. Сначала открепи его.');return}e.preventDefault();const startX=e.clientX,startY=e.clientY;const move=ev=>{if(!drag&&Math.hypot(ev.clientX-startX,ev.clientY-startY)>5){suppress=true;const r=item.getBoundingClientRect();const slot=makeSlot(item),ghost=makeGhost(item,r);item.parentElement.insertBefore(slot,item);item.remove();drag={chatId:item.dataset.chatId,slot,ghost,offsetX:startX-r.left,offsetY:startY-r.top};document.body.classList.add('drag-live')}if(drag){drag.ghost.style.left=ev.clientX-drag.offsetX+'px';drag.ghost.style.top=ev.clientY-drag.offsetY+'px';placeSlot(drag,ev.clientX,ev.clientY);ev.preventDefault()}};const up=ev=>{document.removeEventListener('pointermove',move,true);document.removeEventListener('pointerup',up,true);if(!drag)return;placeSlot(drag,ev.clientX,ev.clientY);const d=drag;flyToSlot(d,()=>{commitDrag(d);d.slot.remove();d.ghost.remove();document.body.classList.remove('drag-live');drag=null;renderChats();setTimeout(()=>suppress=false,20)});ev.preventDefault()};document.addEventListener('pointermove',move,true);document.addEventListener('pointerup',up,true)},true);document.addEventListener('click',e=>{if(suppress){e.preventDefault();e.stopImmediatePropagation();suppress=false}},true)}

function bindDrop(){const feed=$('#feed'),drop=$('#drop');['dragenter','dragover'].forEach(ev=>feed.addEventListener(ev,e=>{if(e.dataTransfer?.types?.includes('Files')){e.preventDefault();drop.classList.add('show')}}));['dragleave','drop'].forEach(ev=>feed.addEventListener(ev,e=>drop.classList.remove('show')));feed.addEventListener('drop',e=>{const f=e.dataTransfer?.files?.[0];if(f){e.preventDefault();previewFile(f)}})}
function bindSidebarSearch(){const input=$('#sidebarSearch');if(!input)return;input.addEventListener('input',()=>{const q=input.value.trim().toLowerCase();$$('[data-chat-id]').forEach(el=>{const title=el.querySelector('.ct')?.textContent?.toLowerCase()||'';el.classList.toggle('ucmu-search-hidden',!!q&&!title.includes(q))})})}
function blinkChatSwitch(){const main=$('.main'),c=findChat(state.activeChat);if(!main)return;main.style.setProperty('--ucmu-active-chat-color',c?.styleColor||c?.color||'#d71920');main.classList.remove('ucmu-chat-blink');void main.offsetWidth;main.classList.add('ucmu-chat-blink')}
function placeStickers(){const s=$('#stickers'),btn=$('#stickerBtn');toggle(s);const r=btn.getBoundingClientRect();s.style.left=Math.max(12,r.left-150)+'px';s.style.right='auto';s.style.bottom=(window.innerHeight-r.top+10)+'px'}
function openFolderModal(existing=null){const name=prompt(existing?'Название папки':'Название папки',existing?.name||'Новая папка');if(name===null)return;if(existing)existing.name=name.trim()||existing.name;else state.folders.push({id:uid('f'),name:name.trim()||'Новая папка',color:'#d71920',open:false,chatIds:[]});renderChats()}
function openCreateChatModal(){const title=prompt('Название чата','Новый чат');if(title===null)return;const id=uid('chat');state.chats.unshift({id,title:title.trim()||'Новый чат',description:'',members:[state.currentUser?.uid||'dev_user'],memberProfiles:{},ownerId:state.currentUser?.uid||'dev_user',createdBy:state.currentUser?.uid||'dev_user',last:'Нет сообщений',time:'сейчас',styleColor:'#d71920'});state.messages[id]=[];state.activeChat=id;renderAll()}
function openContactsPanel(){const panel=$('#members'),title=panel?.querySelector('.ph span'),list=$('#memberList');if(!panel||!list)return;title.textContent='КОНТАКТЫ';list.innerHTML='<div class="reactionEmpty">Контактов пока нет</div>';show(panel)}
