import {state,uid,activeMessages,findChat,findFolder} from './state.js';import {$,$$,show,hide,toggle,placeMenu} from './dom.js';import {renderAll,renderChats,renderFeed,appendMessage} from './render.js';import {appear,pending,restore,removeAnimated,DELETE_DELAY} from './animations.js';
let selectedFile=null;
export function bindActions(){
 $('#collapse').onclick=()=>{const app=$('#app');app.classList.toggle('collapsed');$('#collapse').textContent=app.classList.contains('collapsed')?'›':'‹'};
 $('#menu').onclick=()=>$('#app').classList.toggle('mobile');$('#membersBtn').onclick=()=>toggle($('#members'));$('#closeMembers').onclick=()=>hide($('#members'));
 $('#newChat').onclick=()=>{show($('#members'));show($('#private'))};$('#closePrivate').onclick=()=>hide($('#private'));
 $('#searchBtn').onclick=()=>$('#headerSearch').classList.toggle('show');$('#stickerBtn').onclick=()=>toggle($('#stickers'));
 $('#send').onclick=sendText;$('#input').onkeydown=e=>{if(e.key==='Enter'&&!e.shiftKey){e.preventDefault();sendText()}};
 $('#attach').onclick=()=>$('#fileInput').click();$('#fileInput').onchange=e=>previewFile(e.target.files?.[0]);$('#closeFile').onclick=()=>hide($('#filePreview'));$('#confirmFile').onclick=sendFile;
 $('#folderBtn').onclick=()=>show($('#folderModal'));$('#closeFolder').onclick=()=>hide($('#folderModal'));$('#createFolder').onclick=createFolder;
 $('#closeFolderStyle').onclick=()=>hide($('#folderStyleModal'));$('#saveFolderStyle').onclick=saveFolderStyle;
 $('#cancelDelete').onclick=()=>hide($('#deleteModal'));$('#confirmDelete').onclick=confirmDelete;$('#undoDelete').onclick=undoDelete;
 $('#startPrivate').onclick=startPrivateChat;
 document.addEventListener('click',globalClick,true);document.addEventListener('contextmenu',globalContext,true);bindDrag();bindDrop();renderAll();
}
function sendText(){const input=$('#input'),text=input.value.trim();if(!text)return;if(state.editingId){const m=activeMessages().find(x=>x.id===state.editingId);if(m)m.text=text;state.editingId=null;input.value='';renderFeed();return}appendMessage({id:uid('m'),author:state.user,color:'red',type:'text',text,time:'сейчас',mine:true,reply:state.replyTo});state.replyTo=null;input.value='';updateChatLast(text)}
function previewFile(file){if(!file)return;selectedFile=file;$('#fileName').textContent=file.name;$('#fileSize').textContent=formatSize(file.size);show($('#filePreview'));$('#fileInput').value=''}
function sendFile(){if(!selectedFile)return;appendMessage({id:uid('m'),author:state.user,color:'red',type:'file',text:'',file:selectedFile.name,size:formatSize(selectedFile.size),time:'сейчас',mine:true});updateChatLast('Файл: '+selectedFile.name);selectedFile=null;hide($('#filePreview'))}
function createFolder(){const name=$('#folderName').value.trim()||'Новая папка',folder={id:uid('f'),name,color:'#d71920',open:false,chatIds:[]};state.folders.push(folder);hide($('#folderModal'));renderChats();requestAnimationFrame(()=>appear($(`[data-folder-id="${folder.id}"]`)))}
function saveFolderStyle(){const f=findFolder(state.selectedFolderId);if(!f)return;f.name=$('#folderStyleName').value.trim()||f.name;hide($('#folderStyleModal'));renderChats()}
function startPrivateChat(){const person=$('#private .candidate.active')?.dataset.person||'Alice';let chat=state.chats.find(c=>c.title===person);let created=false;if(!chat){chat={id:uid('chat'),title:person,last:'Новый личный чат',time:'сейчас',unread:1,muted:false};state.chats.unshift(chat);state.messages[chat.id]=[];created=true}state.activeChat=chat.id;hide($('#private'));renderAll();if(created)requestAnimationFrame(()=>appear($(`[data-chat-id="${chat.id}"]`)))}
function globalClick(e){
 if(document.body.classList.contains('drag-live')){e.preventDefault();e.stopPropagation();return}
 const sticker=e.target.closest('[data-sticker]');if(sticker){appendMessage({id:uid('m'),author:state.user,color:'red',type:'sticker',text:sticker.dataset.sticker,time:'сейчас',mine:true});hide($('#stickers'));return}
 const chat=e.target.closest('[data-chat-id]');if(chat&&!e.target.closest('.ctx')){state.activeChat=chat.dataset.chatId;const c=findChat(state.activeChat);if(c)c.unread=0;renderAll();return}
 const folder=e.target.closest('.folder-item');if(folder&&!e.target.closest('[data-chat-id]')){const wrap=folder.closest('[data-folder-id]'),f=wrap&&findFolder(wrap.dataset.folderId);if(f){f.open=!f.open;renderChats()}return}
 const member=e.target.closest('.member');if(member){show($('#members'));show($('#private'));return}
 const candidate=e.target.closest('.candidate');if(candidate){$$('#private .candidate').forEach(x=>x.classList.remove('active'));candidate.classList.add('active');return}
 const ctxAction=e.target.closest('.ctxAction,.reactBtn');if(ctxAction){handleContextAction(ctxAction);return}
 const color=e.target.closest('[data-folder-color]');if(color){const f=findFolder(state.selectedFolderId);if(f){f.color=color.dataset.folderColor;renderChats()}return}
 if(!e.target.closest('.float,.hbtn,#stickerBtn,#membersBtn,#newChat,#folderBtn'))$$('.ctx').forEach(hide);
}
function globalContext(e){const msg=e.target.closest('[data-msg-id]'),chat=e.target.closest('[data-chat-id]'),folder=e.target.closest('[data-folder-id]');if(msg){e.preventDefault();state.selectedMessageId=msg.dataset.msgId;placeMenu($('#ctx'),e.clientX,e.clientY)}else if(chat){e.preventDefault();state.selectedChatId=chat.dataset.chatId;placeMenu($('#chatCtx'),e.clientX,e.clientY)}else if(folder){e.preventDefault();state.selectedFolderId=folder.dataset.folderId;placeMenu($('#folderCtx'),e.clientX,e.clientY)}}
function handleContextAction(btn){const a=btn.dataset.a;if(btn.dataset.react){const m=activeMessages().find(x=>x.id===state.selectedMessageId);if(m)m.reaction=`${btn.dataset.react} 1`;renderFeed();hide($('#ctx'));return}if(btn.classList.contains('chatAction'))return handleChatAction(a);if(btn.classList.contains('folderAction'))return handleFolderAction(a);const m=activeMessages().find(x=>x.id===state.selectedMessageId);if(!m)return;if(a==='reply'){state.replyTo=`${m.author}: ${m.text||m.file||'стикер'}`;$('#input').focus()}if(a==='edit'){state.editingId=m.id;$('#input').value=m.text||'';$('#input').focus()}if(a==='forward'){appendMessage({...m,id:uid('m'),time:'сейчас',mine:true,reply:'Переслано'})}if(a==='delete')openDelete('message',m.id);hide($('#ctx'))}
function handleChatAction(a){const c=findChat(state.selectedChatId);if(!c)return;if(a==='pin'){state.chats=state.chats.filter(x=>x.id!==c.id);state.chats.unshift(c)}if(a==='mute')c.muted=!c.muted;if(a==='folder')addChatToFirstFolder(c.id);if(a==='delete')openDelete('chat',c.id);hide($('#chatCtx'));if(a!=='delete')renderChats()}
function handleFolderAction(a){const f=findFolder(state.selectedFolderId);if(!f)return;if(a==='pin'){state.folders=state.folders.filter(x=>x.id!==f.id);state.folders.unshift(f)}if(a==='mute')f.muted=!f.muted;if(a==='style'){$('#folderStyleName').value=f.name;show($('#folderStyleModal'))}if(a==='delete')openDelete('folder',f.id);hide($('#folderCtx'));if(a!=='delete')renderChats()}
function addChatToFirstFolder(chatId){if(!state.folders.length){const f={id:uid('f'),name:'Оперативные',color:'#d71920',open:false,chatIds:[]};state.folders.push(f);requestAnimationFrame(()=>appear($(`[data-folder-id="${f.id}"]`)))}const f=state.folders[0];if(!f.chatIds.includes(chatId))f.chatIds.push(chatId)}
function openDelete(type,id){state.pendingDelete={type,id};hide($('#deleteModal'));show($('#deleteModal'))}
function selectorFor(p){return p.type==='message'?`[data-msg-id="${p.id}"]`:p.type==='chat'?`[data-chat-id="${p.id}"]`:`[data-folder-id="${p.id}"]`}
function prepRemoveMetrics(el){if(!el)return;const cs=getComputedStyle(el);el.style.setProperty('--ucmu-mt',cs.marginTop||'0px');el.style.setProperty('--ucmu-mb',cs.marginBottom||'14px');el.style.setProperty('--ucmu-pt',cs.paddingTop||'0px');el.style.setProperty('--ucmu-pb',cs.paddingBottom||'0px')}
function confirmDelete(){const p=state.pendingDelete;if(!p)return;const node=$(selectorFor(p));prepRemoveMetrics(node);hide($('#deleteModal'));if(p.type==='message'){const m=activeMessages().find(x=>x.id===p.id);if(m&&!m.mine){finalDelete(p,node);return}}pending(node);showUndo(p.type);clearTimeout(state.undoTimer);state.undoTimer=setTimeout(()=>finalDelete(p,node),DELETE_DELAY)}
function undoDelete(){clearTimeout(state.undoTimer);state.undoTimer=null;state.pendingDelete=null;$$('.ucmu-delete-pending').forEach(restore);hide($('#undoToast'))}
function finalDelete(p,node){clearTimeout(state.undoTimer);state.undoTimer=null;removeAnimated(node,()=>{if(p.type==='message'){state.messages[state.activeChat]=activeMessages().filter(m=>m.id!==p.id);renderFeed()}if(p.type==='chat'){state.chats=state.chats.filter(c=>c.id!==p.id);state.folders.forEach(f=>f.chatIds=f.chatIds.filter(id=>id!==p.id));delete state.messages[p.id];if(state.activeChat===p.id)state.activeChat=state.chats[0]?.id||null;renderAll()}if(p.type==='folder'){const f=findFolder(p.id);if(f){const ids=new Set(f.chatIds);state.chats=state.chats.filter(c=>!ids.has(c.id));ids.forEach(id=>delete state.messages[id]);if(ids.has(state.activeChat))state.activeChat=state.chats[0]?.id||null}state.folders=state.folders.filter(f=>f.id!==p.id);renderAll()}hide($('#undoToast'));state.pendingDelete=null})}
function showUndo(type){$('#undoText').textContent=type==='message'?'Сообщение удаляется':type==='chat'?'Чат удаляется':'Папка и её чаты удаляются';const u=$('#undoToast');u.classList.remove('run');show(u);void u.offsetWidth;u.classList.add('run')}
function updateChatLast(text){const c=findChat(state.activeChat);if(c){c.last=state.user+': '+text;c.time='сейчас';renderChats()}}
function formatSize(size){if(!size)return'0 MB';const mb=size/1024/1024;return mb<1?Math.ceil(size/1024)+' KB':mb.toFixed(1)+' MB'}
function bindDrag(){let drag=null;
 function makeSlot(from){const el=document.createElement('div');el.className='drag-slot';el.style.height=from.offsetHeight+'px';return el}
 function makeGhost(from,r){const g=from.cloneNode(true);g.classList.add('drag-ghost');g.style.cssText=`position:fixed!important;z-index:9999!important;pointer-events:none!important;margin:0!important;width:${r.width}px!important;height:${r.height}px!important;left:${r.left}px!important;top:${r.top}px!important;max-width:${r.width}px!important;min-width:${r.width}px!important;opacity:1!important;`;document.body.appendChild(g);return g}
 function clearTargets(){$$('.folder-drop-target').forEach(x=>x.classList.remove('folder-drop-target'))}
 function currentList(){return drag?.slot?.parentElement||$('#chatList')}
 function movableItems(list=currentList()){return Array.from(list.querySelectorAll('[data-chat-id],.drag-slot'))}
 function rects(list=currentList()){const m=new Map();movableItems(list).forEach(el=>m.set(el,el.getBoundingClientRect()));return m}
 function animateFlip(before,list=currentList()){movableItems(list).forEach(el=>{const b=before.get(el);if(!b)return;const a=el.getBoundingClientRect(),dx=b.left-a.left,dy=b.top-a.top;if(!dx&&!dy)return;el.getAnimations?.().forEach(anim=>anim.cancel());el.animate([{transform:`translate(${dx}px,${dy}px)`},{transform:'translate(0,0)'}],{duration:260,easing:'cubic-bezier(.16,.86,.22,1)',fill:'both'})})}
 function cleanup(){document.body.classList.remove('drag-live');clearTargets();drag=null}
 function restoreSource(){if(!drag)return;drag.slot.replaceWith(drag.source);drag.source.classList.remove('chat-source-hidden')}
 function flyBack(){if(!drag)return;const d=drag,ghost=d.ghost,slot=d.slot,from=ghost.getBoundingClientRect(),to=slot.getBoundingClientRect();const start=performance.now(),dur=240;function step(t){const p=Math.min(1,(t-start)/dur),e=1-Math.pow(1-p,3),x=from.left+(to.left-from.left)*e,y=from.top+(to.top-from.top)*e;ghost.style.setProperty('left',x+'px','important');ghost.style.setProperty('top',y+'px','important');if(p<1&&drag===d)requestAnimationFrame(step);else if(drag===d){restoreSource();ghost.remove();cleanup()}}requestAnimationFrame(step)}
 function commit(x,y){if(!drag)return;updateFolder(x,y);if(!drag.valid){flyBack();return}const {slot,ghost,chatId,folderId}=drag;if(folderId)addChatToFolder(chatId,folderId);else reorderChatsFromDom(chatId,slot.parentElement);slot?.remove();ghost?.remove();cleanup();renderChats()}
 function listFromPoint(x,y){drag.ghost.style.display='none';const el=document.elementFromPoint(x,y);drag.ghost.style.display='';return el?.closest?.('.folder-chat-list,#chatList')}
 function updateSlot(x,y){if(!drag||drag.folderId)return;const list=listFromPoint(x,y)||currentList();if(!list)return;const items=Array.from(list.querySelectorAll('[data-chat-id]'));let target=null,after=false;for(const item of items){const r=item.getBoundingClientRect();if(y<r.top+r.height/2){target=item;after=false;break}target=item;after=true}const before=rects(list);if(target)list.insertBefore(drag.slot,after?target.nextSibling:target);else list.appendChild(drag.slot);animateFlip(before,list);drag.valid=!!list.closest('.side')}
 function updateFolder(x,y){if(!drag)return;drag.ghost.style.display='none';const el=document.elementFromPoint(x,y);drag.ghost.style.display='';const wrap=el?.closest?.('[data-folder-id]'),side=el?.closest?.('.side');clearTargets();drag.folderId=null;drag.valid=!!side;if(wrap&&!el.closest('.folder-chat-list')){wrap.classList.add('folder-drop-target');drag.folderId=wrap.dataset.folderId;drag.valid=true}}
 document.addEventListener('pointerdown',e=>{const item=e.target.closest('[data-chat-id]');if(!item||e.button!==0||e.target.closest('.ctx'))return;e.preventDefault();const startX=e.clientX,startY=e.clientY;const onMove=ev=>{const dx=ev.clientX-startX,dy=ev.clientY-startY;if(!drag&&Math.hypot(dx,dy)>5){const r=item.getBoundingClientRect();drag={source:item,chatId:item.dataset.chatId,slot:makeSlot(item),ghost:makeGhost(item,r),offsetX:startX-r.left,offsetY:startY-r.top,folderId:null,valid:true};document.body.classList.add('drag-live');item.parentElement.insertBefore(drag.slot,item);item.remove()}if(drag){drag.ghost.style.setProperty('left',(ev.clientX-drag.offsetX)+'px','important');drag.ghost.style.setProperty('top',(ev.clientY-drag.offsetY)+'px','important');updateFolder(ev.clientX,ev.clientY);if(!drag.folderId&&drag.valid)updateSlot(ev.clientX,ev.clientY);ev.preventDefault()}};const onUp=ev=>{document.removeEventListener('pointermove',onMove,true);document.removeEventListener('pointerup',onUp,true);if(drag){ev.preventDefault();commit(ev.clientX,ev.clientY)}};document.addEventListener('pointermove',onMove,true);document.addEventListener('pointerup',onUp,true)})}
function reorderChatsFromDom(from,listEl=document.querySelector('#chatList')){const ids=Array.from(listEl.querySelectorAll('[data-chat-id],.drag-slot')).map(el=>el.classList.contains('drag-slot')?from:el.dataset.chatId).filter(Boolean);const folderWrap=listEl.closest('[data-folder-id]');if(folderWrap){const f=findFolder(folderWrap.dataset.folderId);if(f){f.chatIds=[...new Set(ids)];state.folders.forEach(o=>{if(o.id!==f.id)o.chatIds=o.chatIds.filter(id=>id!==from)})}return}const map=new Map(state.chats.map(c=>[c.id,c]));const seen=new Set(),reordered=[];ids.forEach(id=>{if(!seen.has(id)&&map.has(id)){seen.add(id);reordered.push(map.get(id))}});state.chats.forEach(c=>{if(!seen.has(c.id))reordered.push(c)});state.chats=reordered;state.folders.forEach(f=>f.chatIds=f.chatIds.filter(id=>id!==from))}
function addChatToFolder(chatId,folderId){state.folders.forEach(f=>f.chatIds=f.chatIds.filter(id=>id!==chatId));const f=findFolder(folderId);if(f&&!f.chatIds.includes(chatId)){f.chatIds.push(chatId);f.open=false}}
function bindDrop(){const feed=$('#feed'),drop=$('#drop');['dragenter','dragover'].forEach(ev=>feed.addEventListener(ev,e=>{if(e.dataTransfer?.types?.includes('Files')){e.preventDefault();drop.classList.add('show')}}));['dragleave','drop'].forEach(ev=>feed.addEventListener(ev,e=>drop.classList.remove('show')));feed.addEventListener('drop',e=>{const f=e.dataTransfer?.files?.[0];if(f){e.preventDefault();previewFile(f)}})}
