import {state,uid,activeMessages,findChat,findFolder} from './state.js';import {$,$$,show,hide,toggle,placeMenu} from './dom.js';import {renderAll,renderChats,renderFeed,appendMessage,markMessageLocallyGone,unmarkMessageLocallyGone} from './render.js';import {appear,pending,restore,removeAnimated,DELETE_DELAY} from './animations.js';import {sendStoreMessage,isChatStoreReady,subscribeMessages,deleteStoreMessageForMe,deleteStoreMessageForAll} from './chatStore.js';
let selectedFile=null;
function toast(text){let el=document.getElementById('fireDebugToast');if(!el){el=document.createElement('div');el.id='fireDebugToast';el.style.cssText='position:fixed;left:50%;bottom:22px;transform:translateX(-50%);z-index:99999;background:rgba(10,12,12,.96);color:#fff;border:1px solid rgba(255,255,255,.18);padding:10px 14px;box-shadow:0 12px 40px rgba(0,0,0,.55);font:12px system-ui;max-width:min(520px,calc(100vw - 28px));white-space:pre-wrap;pointer-events:none';document.body.appendChild(el)}el.textContent=text;clearTimeout(el._t);el._t=setTimeout(()=>el.remove(),4200)}
function sleep(ms){return new Promise(r=>setTimeout(r,ms))}
export function bindActions(){
 $('#collapse').onclick=()=>{const app=$('#app');app.classList.toggle('collapsed');$('#collapse').textContent=app.classList.contains('collapsed')?'›':'‹'};
 $('#menu').onclick=()=>$('#app').classList.toggle('mobile');$('#membersBtn').onclick=()=>toggle($('#members'));$('#closeMembers').onclick=()=>hide($('#members'));
 $('#newChat').onclick=e=>{e.preventDefault()};$('#closePrivate').onclick=()=>hide($('#private'));
 $('#searchBtn').onclick=()=>$('#headerSearch').classList.toggle('show');$('#stickerBtn').onclick=()=>toggle($('#stickers'));
 $('#send').onclick=sendText;$('#input').onkeydown=e=>{if(e.key==='Enter'&&!e.shiftKey){e.preventDefault();sendText()}};
 $('#attach').onclick=()=>$('#fileInput').click();$('#fileInput').onchange=e=>previewFile(e.target.files?.[0]);$('#closeFile').onclick=()=>hide($('#filePreview'));$('#confirmFile').onclick=sendFile;
 $('#folderBtn').onclick=()=>show($('#folderModal'));$('#closeFolder').onclick=()=>hide($('#folderModal'));$('#createFolder').onclick=createFolder;
 $('#closeFolderStyle').onclick=()=>hide($('#folderStyleModal'));$('#saveFolderStyle').onclick=saveFolderStyle;
 $('#cancelDelete').onclick=()=>hide($('#deleteModal'));$('#confirmDelete').onclick=confirmDelete;$('#undoDelete').onclick=undoDelete;
 $('#startPrivate').onclick=startPrivateChat;
 document.addEventListener('click',globalClick,true);document.addEventListener('contextmenu',globalContext,true);bindDrag();bindDrop();renderAll();
}
async function sendText(){const input=$('#input'),text=input.value.trim();if(!text)return;if(state.editingId){const m=activeMessages().find(x=>x.id===state.editingId);if(m)m.text=text;state.editingId=null;input.value='';renderFeed();return}const reply=state.replyTo;state.replyTo=null;input.value='';if(isChatStoreReady()){try{await sendStoreMessage({type:'text',text,replyTo:reply});return}catch(err){console.error('send text failed',err);toast('Не удалось отправить сообщение:\n'+(err.message||err.code||err))}}appendMessage({id:uid('m'),author:state.user,color:'red',type:'text',text,time:'сейчас',mine:true,reply});updateChatLast(text)}
function previewFile(file){if(!file)return;selectedFile=file;$('#fileName').textContent=file.name;$('#fileSize').textContent=formatSize(file.size);show($('#filePreview'));$('#fileInput').value=''}
function sendFile(){if(!selectedFile)return;appendMessage({id:uid('m'),author:state.user,color:'red',type:'file',text:'',file:selectedFile.name,size:formatSize(selectedFile.size),time:'сейчас',mine:true});updateChatLast('Файл: '+selectedFile.name);selectedFile=null;hide($('#filePreview'))}
function createFolder(){const name=$('#folderName').value.trim()||'Новая папка',folder={id:uid('f'),name,color:'#d71920',open:false,chatIds:[]};state.folders.push(folder);hide($('#folderModal'));renderChats();requestAnimationFrame(()=>appear($(`[data-folder-id="${folder.id}"]`)))}
function saveFolderStyle(){const f=findFolder(state.selectedFolderId);if(!f)return;f.name=$('#folderStyleName').value.trim()||f.name;hide($('#folderStyleModal'));renderChats()}
function startPrivateChat(){hide($('#private'))}
async function globalClick(e){
 if(document.body.classList.contains('drag-live')){e.preventDefault();e.stopPropagation();return}
 const sticker=e.target.closest('[data-sticker]');if(sticker){const text=sticker.dataset.sticker;hide($('#stickers'));if(isChatStoreReady()){try{await sendStoreMessage({type:'sticker',text});return}catch(err){console.error('send sticker failed',err);toast('Не удалось отправить стикер:\n'+(err.message||err.code||err))}}appendMessage({id:uid('m'),author:state.user,color:'red',type:'sticker',text,time:'сейчас',mine:true});return}
 const chat=e.target.closest('[data-chat-id]');if(chat&&!e.target.closest('.ctx')){state.activeChat=chat.dataset.chatId;const c=findChat(state.activeChat);if(c)c.unread=0;renderAll();if(isChatStoreReady())subscribeMessages(state.activeChat);return}
 const folder=e.target.closest('.folder-item');if(folder&&!e.target.closest('[data-chat-id]')){const wrap=folder.closest('[data-folder-id]'),f=wrap&&findFolder(wrap.dataset.folderId);if(f){f.open=!f.open;renderChats()}return}
 const member=e.target.closest('.member');if(member){return}
 const candidate=e.target.closest('.candidate');if(candidate){$$('#private .candidate').forEach(x=>x.classList.remove('active'));candidate.classList.add('active');return}
 const ctxAction=e.target.closest('.ctxAction,.reactBtn');if(ctxAction){handleContextAction(ctxAction);return}
 const color=e.target.closest('[data-folder-color]');if(color){const f=findFolder(state.selectedFolderId);if(f){f.color=color.datasetFolderColor||color.dataset.folderColor;renderChats()}return}
 if(!e.target.closest('.float,.hbtn,#stickerBtn,#membersBtn,#newChat,#folderBtn'))$$('.ctx').forEach(hide);
}
function globalContext(e){if(e.target.closest('.reactChip'))return;const msg=e.target.closest('[data-msg-id]'),chat=e.target.closest('[data-chat-id]'),folder=e.target.closest('[data-folder-id]');if(msg){e.preventDefault();state.selectedMessageId=msg.dataset.msgId;placeMenu($('#ctx'),e.clientX,e.clientY)}else if(chat){e.preventDefault();state.selectedChatId=chat.dataset.chatId;placeMenu($('#chatCtx'),e.clientX,e.clientY);const pinBtn=$('#chatCtx .chatAction[data-a="pin"]');const c=findChat(state.selectedChatId);if(pinBtn&&c)pinBtn.textContent=c.pinned?'📌 Открепить':'📌 Закрепить'}else if(folder){e.preventDefault();state.selectedFolderId=folder.dataset.folderId;placeMenu($('#folderCtx'),e.clientX,e.clientY)}}
function handleContextAction(btn){const a=btn.dataset.a;if(btn.dataset.react){return}if(btn.classList.contains('chatAction'))return handleChatAction(a);if(btn.classList.contains('folderAction'))return handleFolderAction(a);const m=activeMessages().find(x=>x.id===state.selectedMessageId);if(!m)return;if(a==='reply'){state.replyTo=`${m.author}: ${m.text||m.file||'стикер'}`;$('#input').focus()}if(a==='edit'){state.editingId=m.id;$('#input').value=m.text||'';$('#input').focus()}if(a==='forward'){appendMessage({...m,id:uid('m'),time:'сейчас',mine:true,reply:'Переслано'})}if(a==='delete')openDelete('message',m.id);hide($('#ctx'))}
function handleChatAction(a){const c=findChat(state.selectedChatId);if(!c)return;if(a==='pin'){c.pinned=!c.pinned;if(c.pinned){state.chats=state.chats.filter(x=>x.id!==c.id);state.chats.unshift(c)}}if(a==='mute')c.muted=!c.muted;if(a==='folder')addChatToFirstFolder(c.id);if(a==='delete')openDelete('chat',c.id);hide($('#chatCtx'));if(a!=='delete')renderChats()}
function handleFolderAction(a){const f=findFolder(state.selectedFolderId);if(!f)return;if(a==='pin'){state.folders=state.folders.filter(x=>x.id!==f.id);state.folders.unshift(f)}if(a==='mute')f.muted=!f.muted;if(a==='style'){$('#folderStyleName').value=f.name;show($('#folderStyleModal'))}if(a==='delete')openDelete('folder',f.id);hide($('#folderCtx'));if(a!=='delete')renderChats()}
function addChatToFirstFolder(chatId){if(!state.folders.length){const f={id:uid('f'),name:'Оперативные',color:'#d71920',open:false,chatIds:[]};state.folders.push(f);requestAnimationFrame(()=>appear($(`[data-folder-id="${f.id}"]`)))}const f=state.folders[0];if(!f.chatIds.includes(chatId))f.chatIds.push(chatId)}
function openDelete(type,id){state.pendingDelete={type,id};const row=$('.deleteAllRow'),check=$('#deleteForAll');if(row&&check){row.style.display=type==='message'?'flex':'none';check.checked=false;if(type==='message'){const m=activeMessages().find(x=>x.id===id);if(m&&!m.mine){row.style.display='none';check.checked=false}}}hide($('#deleteModal'));const modal=$('#deleteModal');if(type==='chat'){modal.classList.add('rowDelete');const target=$(`[data-chat-id="${id}"]`);const r=target?.getBoundingClientRect();if(r){modal.style.left=Math.min(window.innerWidth-270,r.right+10)+'px';modal.style.top=Math.max(12,Math.min(window.innerHeight-140,r.top))+'px'}}else{modal.classList.remove('rowDelete');modal.style.left='';modal.style.top=''}show(modal)}
function selectorFor(p){return p.type==='message'?`[data-msg-id="${p.id}"]`:p.type==='chat'?`[data-chat-id="${p.id}"]`:`[data-folder-id="${p.id}"]`}
function prepRemoveMetrics(el){if(!el)return;const cs=getComputedStyle(el);el.style.setProperty('--ucmu-mt',cs.marginTop||'0px');el.style.setProperty('--ucmu-mb',cs.marginBottom||'14px');el.style.setProperty('--ucmu-pt',cs.paddingTop||'0px');el.style.setProperty('--ucmu-pb',cs.paddingBottom||'0px')}
function showUndo(type){$('#undoText').textContent=type==='message'?'Сообщение удалено':type==='chat'?'Чат удаляется':'Папка и её чаты удаляются';const u=$('#undoToast');u.classList.remove('run');show(u);void u.offsetWidth;u.classList.add('run')}
async function stageDeleteMessage(p,node,forAll){const chatId=state.activeChat;const original=activeMessages().find(x=>x.id===p.id);prepRemoveMetrics(node);markMessageLocallyGone(p.id);if(node)removeAnimated(node);await sleep(900);if(state.messages[chatId])state.messages[chatId]=state.messages[chatId].filter(x=>x.id!==p.id);renderFeed();state.pendingDeleteCommit={...p,chatId,forAll,original};showUndo('message');clearTimeout(state.undoTimer);state.undoTimer=setTimeout(async()=>{const commit=state.pendingDeleteCommit;state.pendingDeleteCommit=null;hide($('#undoToast'));if(!commit)return;try{if(commit.forAll)await deleteStoreMessageForAll(commit.id);else await deleteStoreMessageForMe(commit.id);toast(commit.forAll?'Удалено для всех':'Удалено у вас')}catch(err){if(commit.original){state.messages[commit.chatId]||=[];if(!state.messages[commit.chatId].some(x=>x.id===commit.id))state.messages[commit.chatId].push(commit.original)}unmarkMessageLocallyGone(commit.id);renderFeed();toast('Не удалось удалить:\n'+(err.message||err.code||err))}},3000)}
async function confirmDelete(){const p=state.pendingDelete;if(!p)return;const node=$(selectorFor(p));hide($('#deleteModal'));$('#deleteModal').classList.remove('rowDelete');
 if(p.type==='message'&&isChatStoreReady()){const m=activeMessages().find(x=>x.id===p.id);const forAll=$('#deleteForAll')?.checked&&m?.mine;state.pendingDelete=null;await stageDeleteMessage(p,node,forAll);return}
 if(p.type==='message'){const m=activeMessages().find(x=>x.id===p.id);if(m&&!m.mine){finalDelete(p,node);return}}pending(node);showUndo(p.type);clearTimeout(state.undoTimer);state.undoTimer=setTimeout(()=>finalDelete(p,node),p.type==='chat'?500:DELETE_DELAY)}
function undoDelete(){clearTimeout(state.undoTimer);state.undoTimer=null;if(state.pendingDeleteCommit?.type==='message'){const commit=state.pendingDeleteCommit;state.pendingDeleteCommit=null;if(commit.original){state.messages[commit.chatId]||=[];if(!state.messages[commit.chatId].some(x=>x.id===commit.id))state.messages[commit.chatId].push(commit.original);state.messages[commit.chatId].sort((a,b)=>(a.time||'').localeCompare(b.time||''))}unmarkMessageLocallyGone(commit.id);if(state.activeChat!==commit.chatId)state.activeChat=commit.chatId;renderFeed();hide($('#undoToast'));return}state.pendingDelete=null;$$('.ucmu-delete-pending').forEach(restore);hide($('#undoToast'))}
function finalDelete(p,node){clearTimeout(state.undoTimer);state.undoTimer=null;removeAnimated(node,()=>{if(p.type==='message'){state.messages[state.activeChat]=activeMessages().filter(m=>m.id!==p.id);renderFeed()}if(p.type==='chat'){state.chats=state.chats.filter(c=>c.id!==p.id);state.folders.forEach(f=>f.chatIds=f.chatIds.filter(id=>id!==p.id));delete state.messages[p.id];if(state.activeChat===p.id)state.activeChat=state.chats[0]?.id||null;renderAll()}if(p.type==='folder'){const f=findFolder(p.id);if(f){const ids=new Set(f.chatIds);state.chats=state.chats.filter(c=>!ids.has(c.id));ids.forEach(id=>delete state.messages[id]);if(ids.has(state.activeChat))state.activeChat=state.chats[0]?.id||null}state.folders=state.folders.filter(f=>f.id!==p.id);renderAll()}hide($('#undoToast'));state.pendingDelete=null})}
function updateChatLast(text){const c=findChat(state.activeChat);if(c){c.last=state.user+': '+text;c.time='сейчас';renderChats()}}
function formatSize(size){if(!size)return'0 MB';const mb=size/1024/1024;return mb<1?Math.ceil(size/1024)+' KB':mb.toFixed(1)+' MB'}
function bindDrag(){let drag=null;
 function makeSlot(from){const el=document.createElement('div');el.className='drag-slot';el.style.height=from.offsetHeight+'px';return el}
 function makeGhost(from,r){const g=from.cloneNode(true);g.classList.add('drag-ghost');g.style.cssText=`position:fixed!important;z-index:9999!important;pointer-events:none!important;margin:0!important;width:${r.width}px!important;height:${r.height}px!important;left:${r.left}px!important;top:${r.top}px!important;max-width:${r.width}px!important;min-width:${r.width}px!important;opacity:1!important;`;document.body.appendChild(g);return g}
 function clearTargets(){$$('.folder-drop-target').forEach(x=>x.classList.remove('folder-drop-target'))}
 function currentList(){return drag?.slot?.parentElement||$('#chatList')}
 function movableItems(list=currentList()){return Array.from(list.querySelectorAll('[data-chat-id],.drag-slot'))}
 function rects(list=currentList()){const m=new Map();movableItems(list).forEach(el=>m.set(el,el.getBoundingClientRect()));return m}
 function animateFlip(before,list=currentList()){movableItems(list).forEach(el=>{const b=before.get(el);if(!b)return;const a=el.getBoundingClientRect(),dx=b.left-a.left,dy=b.top-a.top;if(!dx&&!dy)return;el.getAnimations?.().forEach(anim=>anim.cancel());el.animate([{transform:`translate(${dx}px,${dy}px)`},{transform:'translate(0,0)'}],{duration:260,easing:'cubic-bezier(.16,.86,.22,1)',fill:'both'})})}
 function cleanup(){document.body.classList.remove('drag-live');clearTargets();drag=null}
 function restoreSource(){if(!drag)return;drag.slot.replaceWith(drag.source);drag.source.classList.remove('chat-source-hidden')}
 function flyBack(){if(!drag)return;const d=drag,ghost=d.ghost,slot=d.slot,from=ghost.getBoundingClientRect(),to=slot.getBoundingClientRect();const start=performance.now(),dur=240;function step(t){const p=Math.min(1,(t-start)/dur),e=1-Math.pow(1-p,3),x=from.left+(to.left-from.left)*e,y=from.top+(to.top-from.top)*e;ghost.style.setProperty('left',x+'px','important');ghost.style.setProperty('top',y+'px','important');if(p<1&&drag===d)requestAnimationFrame(step);else if(drag===d){restoreSource();ghost.remove();cleanup()}}requestAnimationFrame(step)}
 function commit(x,y){if(!drag)return;updateFolder(x,y);if(!drag.valid){flyBack();return}const {slot,ghost,chatId,folderId}=drag;if(folderId)addChatToFolder(chatId,folderId);else reorderChatsFromDom(chatId,slot.parentElement);slot?.remove();ghost?.remove();cleanup();renderChats()}
 function listFromPoint(x,y){drag.ghost.style.display='none';const el=document.elementFromPoint(x,y);drag.ghost.style.display='';if(!el)return currentList();const exact=el.closest('.folder-chat-list,#chatList');if(exact)return exact;const side=el.closest('.side');const folderItem=el.closest('.folder-item');if(side&&!folderItem)return $('#chatList');return currentList()}
 function updateSlot(x,y){if(!drag||drag.folderId)return;const list=listFromPoint(x,y)||currentList();if(!list)return;const items=Array.from(list.querySelectorAll('[data-chat-id]'));let target=null,after=false;for(const item of items){const r=item.getBoundingClientRect();if(y<r.top+r.height/2){target=item;after=false;break}target=item;after=true}const before=rects(list);if(target)list.insertBefore(drag.slot,after?target.nextSibling:target);else list.appendChild(drag.slot);animateFlip(before,list);drag.valid=!!list.closest('.side')}
 function updateFolder(x,y){if(!drag)return;drag.ghost.style.display='none';const el=document.elementFromPoint(x,y);drag.ghost.style.display='';const wrap=el?.closest?.('[data-folder-id]'),side=el?.closest?.('.side'),folderList=el?.closest?.('.folder-chat-list');clearTargets();drag.folderId=null;drag.valid=!!side;if(wrap&&!folderList&&el?.closest?.('.folder-item')){wrap.classList.add('folder-drop-target');drag.folderId=wrap.dataset.folderId;drag.valid=true}}
 document.addEventListener('pointerdown',e=>{const item=e.target.closest('[data-chat-id]');if(!item||e.button!==0||e.target.closest('.ctx'))return;const c=findChat(item.dataset.chatId);if(c?.pinned){toast('Закреплённый чат нельзя таскать. Сначала открепи его.');return}e.preventDefault();const startX=e.clientX,startY=e.clientY;const onMove=ev=>{const dx=ev.clientX-startX,dy=ev.clientY-startY;if(!drag&&Math.hypot(dx,dy)>5){const r=item.getBoundingClientRect();drag={source:item,chatId:item.dataset.chatId,slot:makeSlot(item),ghost:makeGhost(item,r),offsetX:startX-r.left,offsetY:startY-r.top,folderId:null,valid:true};document.body.classList.add('drag-live');item.parentElement.insertBefore(drag.slot,item);item.remove()}if(drag){drag.ghost.style.setProperty('left',(ev.clientX-drag.offsetX)+'px','important');drag.ghost.style.setProperty('top',(ev.clientY-drag.offsetY)+'px','important');updateFolder(ev.clientX,ev.clientY);if(!drag.folderId&&drag.valid)updateSlot(ev.clientX,ev.clientY);ev.preventDefault()}};const onUp=ev=>{document.removeEventListener('pointermove',onMove,true);document.removeEventListener('pointerup',onUp,true);if(drag){ev.preventDefault();commit(ev.clientX,ev.clientY)}};document.addEventListener('pointermove',onMove,true);document.addEventListener('pointerup',onUp,true)})}
function reorderChatsFromDom(from,listEl=document.querySelector('#chatList')){const ids=Array.from(listEl.querySelectorAll('[data-chat-id],.drag-slot')).map(el=>el.classList.contains('drag-slot')?from:el.dataset.chatId).filter(Boolean);const folderWrap=listEl.closest('[data-folder-id]');if(folderWrap){const f=findFolder(folderWrap.dataset.folderId);if(f){f.chatIds=[...new Set(ids)];state.folders.forEach(o=>{if(o.id!==f.id)o.chatIds=o.chatIds.filter(id=>id!==from)})}return}const map=new Map(state.chats.map(c=>[c.id,c]));const seen=new Set(),reordered=[];ids.forEach(id=>{if(!seen.has(id)&&map.has(id)){seen.add(id);reordered.push(map.get(id))}});state.chats.filter(c=>c.pinned&&!seen.has(c.id)).forEach(c=>reordered.unshift(c));state.chats.forEach(c=>{if(!seen.has(c.id)&&!c.pinned)reordered.push(c)});state.chats=reordered;state.folders.forEach(f=>f.chatIds=f.chatIds.filter(id=>id!==from))}
function addChatToFolder(chatId,folderId){state.folders.forEach(f=>f.chatIds=f.chatIds.filter(id=>id!==chatId));const f=findFolder(folderId);if(f&&!f.chatIds.includes(chatId)){f.chatIds.push(chatId);f.open=false}}
function bindDrop(){const feed=$('#feed'),drop=$('#drop');['dragenter','dragover'].forEach(ev=>feed.addEventListener(ev,e=>{if(e.dataTransfer?.types?.includes('Files')){e.preventDefault();drop.classList.add('show')}}));['dragleave','drop'].forEach(ev=>feed.addEventListener(ev,e=>drop.classList.remove('show')));feed.addEventListener('drop',e=>{const f=e.dataTransfer?.files?.[0];if(f){e.preventDefault();previewFile(f)}})}
