import {state} from './state.js';
import {getFirebase} from './firebase.js';
import {renderChats, renderFeed} from './render.js';
import {
  collection, doc, getDoc, getDocs, setDoc, addDoc, updateDoc,
  query, where, orderBy, limit, onSnapshot, serverTimestamp, arrayUnion
} from 'https://www.gstatic.com/firebasejs/10.14.1/firebase-firestore.js';
let db=null,chatsUnsub=null,messagesUnsub=null,subscribedChatId=null,ready=false;
let localSeq=0;
const pendingMessages=new Map();
function toast(text){let el=document.getElementById('fireDebugToast');if(!el){el=document.createElement('div');el.id='fireDebugToast';el.style.cssText='position:fixed;left:50%;bottom:22px;transform:translateX(-50%);z-index:99999;background:rgba(10,12,12,.96);color:#fff;border:1px solid rgba(255,255,255,.18);padding:10px 14px;box-shadow:0 12px 40px rgba(0,0,0,.55);font:12px system-ui;max-width:min(520px,calc(100vw - 28px));white-space:pre-wrap;pointer-events:none';document.body.appendChild(el)}el.textContent=text;clearTimeout(el._t);el._t=setTimeout(()=>el.remove(),5200)}
const sleep=ms=>new Promise(r=>setTimeout(r,ms));
function currentUid(){return state.currentUser?.uid}
function displayName(){return state.currentUser?.displayName||state.currentUser?.username||state.user||'Operator'}
function profileForCurrentUser(){return{uid:currentUid(),displayName:displayName(),username:state.currentUser?.username||'',email:state.currentUser?.email||''}}
function normalizeUsername(v){return String(v||'').trim().toLowerCase().replace(/^@/,'')}
function messageTime(data){const d=data.createdAt?.toDate?.();if(!d)return'сейчас';return String(d.getHours()).padStart(2,'0')+':'+String(d.getMinutes()).padStart(2,'0')}
function chatTime(data){const d=data.updatedAt?.toDate?.()||data.createdAt?.toDate?.();if(!d)return'сейчас';const today=new Date();if(d.toDateString()!==today.toDateString())return'Вчера';return String(d.getHours()).padStart(2,'0')+':'+String(d.getMinutes()).padStart(2,'0')}
function mapChat(snap){const d=snap.data();return{id:snap.id,title:d.title||'Чат',description:d.description||d.desc||'',last:d.lastText||'Нет сообщений',time:chatTime(d),unread:0,muted:false,members:d.members||[],memberProfiles:d.memberProfiles||{},ownerId:d.ownerId||d.createdBy||null,createdBy:d.createdBy||d.ownerId||null,type:d.type||'group',styleColor:d.styleColor||d.color||'#d71920'}}
function mapMessage(snap){const d=snap.data();if(d.deletedForAll===true)return null;const deletedFor=d.deletedFor||[];if(currentUid()&&deletedFor.includes(currentUid()))return null;return{id:snap.id,author:d.authorName||'User',authorId:d.authorId,color:d.authorId===currentUid()?'red':'green',type:d.type||'text',text:d.text||'',file:d.file||'',size:d.size||'',time:messageTime(d),mine:d.authorId===currentUid(),reactions:d.reactions||{},reply:d.replyTo||null,deletingForAll:d.deletingForAll===true,localSeq:d.localSeq||0}}
function localMessage({id,type='text',text='',file='',size='',replyTo=null,seq=0}={}){return{id,author:displayName(),authorId:currentUid(),color:'red',type,text:text||'',file:file||'',size:size||'',time:'сейчас',mine:true,reactions:{},reply:replyTo||null,deletingForAll:false,pending:true,pendingAt:Date.now(),localSeq:seq}}
function previewText(m){if(!m)return'Нет сообщений';if(m.type==='sticker')return `${m.author}: ${m.text||'стикер'}`;if(m.file)return `${m.author}: ${m.file}`;return `${m.author}: ${m.text||'сообщение'}`}
function syncChatPreview(chatId,messages){const c=state.chats.find(x=>x.id===chatId);if(!c)return;const last=messages[messages.length-1];const next=last?previewText(last):'Нет сообщений';if(c.last!==next){c.last=next;renderChats()}}
function rememberPending(chatId,msg){if(!chatId||!msg?.id)return;const key=chatId+'::'+msg.id;pendingMessages.set(key,msg);setTimeout(()=>pendingMessages.delete(key),20000)}
function mergePending(chatId,next){const now=Date.now();const ids=new Set(next.map(m=>m.id));const merged=[...next];const pending=[...pendingMessages.entries()].filter(([key,msg])=>{const [cid,id]=key.split('::');if(cid!==chatId)return false;if(ids.has(id)){pendingMessages.delete(key);return false}if(now-(msg.pendingAt||0)>=20000){pendingMessages.delete(key);return false}return true}).map(([,msg])=>msg).sort((a,b)=>(a.localSeq||0)-(b.localSeq||0));merged.push(...pending);return merged}
function pushLocalMessage(chatId,msg){if(!chatId||!msg?.id)return;rememberPending(chatId,msg);state.messages[chatId]||=[];const list=state.messages[chatId];if(!list.some(m=>m.id===msg.id))list.push(msg);state.messages[chatId]=list.sort((a,b)=>{const as=a.localSeq||0,bs=b.localSeq||0;if(as&&bs)return as-bs;if(as&&!bs)return 1;if(!as&&bs)return -1;return 0});syncChatPreview(chatId,state.messages[chatId]);if(window.__ucmuLocallyGoneMsgIds?.has?.(msg.id))window.__ucmuLocallyGoneMsgIds.delete(msg.id);if(window.__ucmuClearAnimatingChatId===chatId)delete window.__ucmuClearAnimatingChatId;if(state.activeChat===chatId)renderFeed()}
async function ensureGeneralChat(){const uid=currentUid();if(!uid||!db)return;const ref=doc(db,'chats','general');const snap=await getDoc(ref);const profile=profileForCurrentUser();if(!snap.exists()){await setDoc(ref,{title:'# Общий чат',description:'',type:'group',members:[uid],memberProfiles:{[uid]:profile},ownerId:uid,createdBy:uid,createdAt:serverTimestamp(),updatedAt:serverTimestamp(),lastText:'Чат создан',styleColor:'#d71920'});return}const data=snap.data()||{};const updates={updatedAt:serverTimestamp()};let changed=false;const members=data.members||[];if(!members.includes(uid)){updates.members=arrayUnion(uid);changed=true}if(!data.ownerId){updates.ownerId=uid;changed=true}if(!data.createdBy){updates.createdBy=uid;changed=true}if(!data.memberProfiles?.[uid]?.displayName&&!data.memberProfiles?.[uid]?.username&&!data.memberProfiles?.[uid]?.email){updates[`memberProfiles.${uid}`]=profile;changed=true}if(changed)await updateDoc(ref,updates)}
export async function initChatStore(){const uid=currentUid();if(!uid)return;const fb=await getFirebase();db=fb.db;state.chats=[];state.folders=[];state.messages={};state.activeChat=null;subscribedChatId=null;messagesUnsub?.();messagesUnsub=null;pendingMessages.clear();renderChats();renderFeed();try{await ensureGeneralChat()}catch(err){console.error('[UCMU] ensureGeneralChat failed',err);toast('Firestore: не удалось подключить общий чат.\n'+(err.message||err.code||err))}ready=true;subscribeChats()}
export function isChatStoreReady(){return ready&&!!db&&!!currentUid()}
export function subscribeChats(){if(!isChatStoreReady())return;chatsUnsub?.();const q=query(collection(db,'chats'),where('members','array-contains',currentUid()),orderBy('updatedAt','desc'),limit(50));chatsUnsub=onSnapshot(q,snap=>{const next=snap.docs.map(mapChat);state.chats=next;state.folders=state.folders.filter(f=>f.chatIds.some(id=>state.chats.some(c=>c.id===id)));if(!state.activeChat||!state.chats.some(c=>c.id===state.activeChat))state.activeChat=state.chats[0]?.id||null;renderChats();if(state.activeChat)subscribeMessages(state.activeChat);else{messagesUnsub?.();messagesUnsub=null;subscribedChatId=null;state.messages={};renderFeed()}},err=>{console.error('[UCMU] subscribeChats failed',err);toast('Firestore chats error:\n'+(err.message||err.code||err))})}
export function subscribeMessages(chatId,force=false){if(!isChatStoreReady()||!chatId)return;if(!force&&subscribedChatId===chatId&&messagesUnsub)return;messagesUnsub?.();messagesUnsub=null;subscribedChatId=chatId;const q=query(collection(db,'chats',chatId,'messages'),orderBy('createdAt','asc'),limit(200));messagesUnsub=onSnapshot(q,snap=>{const next=mergePending(chatId,snap.docs.map(mapMessage).filter(Boolean));state.messages[chatId]=next;syncChatPreview(chatId,next);if(window.__ucmuClearAnimatingChatId===chatId){return}if(state.activeChat===chatId)renderFeed()},err=>{console.error('[UCMU] subscribeMessages failed for '+chatId,err);messagesUnsub=null;subscribedChatId=null;toast('Firestore messages error for '+chatId+':\n'+(err.message||err.code||err))})}
export async function sendStoreMessage({type='text',text='',file='',size='',replyTo=null}={}){if(!isChatStoreReady()){toast('Firestore не готов: сообщение ушло только в локальный UI.');return false}const chatId=state.activeChat;if(!chatId){toast('Нет activeChat — некуда отправлять.');return false}const seq=++localSeq;const payload={authorId:currentUid(),authorName:displayName(),type,text:text||'',createdAt:serverTimestamp(),updatedAt:serverTimestamp(),deletedFor:[],deletedForAll:false,deletingForAll:false,reactions:{},localSeq:seq};if(file)payload.file=file;if(size)payload.size=size;if(replyTo)payload.replyTo=replyTo;const ref=await addDoc(collection(db,'chats',chatId,'messages'),payload);pushLocalMessage(chatId,localMessage({id:ref.id,type,text,file,size,replyTo,seq}));updateDoc(doc(db,'chats',chatId),{lastText:type==='sticker'?`${displayName()}: ${text}`:`${displayName()}: ${text||file||'сообщение'}`,updatedAt:serverTimestamp()}).catch(err=>console.error('[UCMU] update lastText failed',err));return true}
export async function createStandaloneChat({title='Новый чат',description='',styleColor='#d71920'}={}){if(!isChatStoreReady())return null;const uid=currentUid();const chatId='chat_'+Date.now().toString(36)+'_'+Math.random().toString(36).slice(2,7);await setDoc(doc(db,'chats',chatId),{title,description,type:'group',members:[uid],memberProfiles:{[uid]:profileForCurrentUser()},ownerId:uid,createdBy:uid,createdAt:serverTimestamp(),updatedAt:serverTimestamp(),lastText:'Чат создан',styleColor});state.activeChat=chatId;subscribeMessages(chatId,true);renderChats();renderFeed();return chatId}
export async function searchUsersByUsername(username){if(!isChatStoreReady())return[];const u=normalizeUsername(username);if(!u||u.length<2)return[];const direct=await getDoc(doc(db,'usernames',u)).catch(()=>null);let found=[];if(direct?.exists?.()){const uid=direct.data().uid||direct.data().userId;if(uid){const us=await getDoc(doc(db,'users',uid));if(us.exists())found.push({uid,...us.data()})}}if(!found.length){const snap=await getDocs(query(collection(db,'users'),where('username','==',u),limit(8)));found=snap.docs.map(d=>({uid:d.id,...d.data()}))}return found.filter(x=>x.uid!==currentUid())}
export async function listKnownUsers(){if(!isChatStoreReady())return[];const known=new Map();state.chats.forEach(c=>Object.entries(c.memberProfiles||{}).forEach(([uid,p])=>{if(uid!==currentUid())known.set(uid,{uid,...p})}));if(known.size)return[...known.values()];const snap=await getDocs(query(collection(db,'users'),limit(30)));return snap.docs.map(d=>({uid:d.id,...d.data()})).filter(x=>x.uid!==currentUid())}
export async function createOrOpenChatWithUsers(users){if(!isChatStoreReady())return null;const clean=(users||[]).filter(Boolean).filter(u=>u.uid&&u.uid!==currentUid());if(!clean.length)return createStandaloneChat();const memberIds=[currentUid(),...clean.map(u=>u.uid)].sort();const chatId=memberIds.length===2?'private_'+memberIds.join('_'):('group_'+Date.now().toString(36)+'_'+Math.random().toString(36).slice(2,7));const exists=await getDoc(doc(db,'chats',chatId));if(!exists.exists()){const profiles={[currentUid()]:profileForCurrentUser()};clean.forEach(u=>profiles[u.uid]={uid:u.uid,displayName:u.displayName||u.username||u.email||'User',username:u.username||'',email:u.email||''});const title=clean.length===1?(clean[0].displayName||clean[0].username||clean[0].email||'Личный чат'):clean.map(u=>u.displayName||u.username||'User').join(', ');await setDoc(doc(db,'chats',chatId),{title,description:'',type:clean.length===1?'private':'group',members:memberIds,memberProfiles:profiles,ownerId:currentUid(),createdBy:currentUid(),createdAt:serverTimestamp(),updatedAt:serverTimestamp(),lastText:'Чат создан',styleColor:'#d71920'})}state.activeChat=chatId;subscribeMessages(chatId,true);renderChats();renderFeed();return chatId}
export async function updateActiveChatMeta({title,description,styleColor}){if(!isChatStoreReady()||!state.activeChat)return;await updateDoc(doc(db,'chats',state.activeChat),{title:title||'Чат',description:description||'',styleColor:styleColor||'#d71920',updatedAt:serverTimestamp()})}
export async function clearActiveChatHistory(){if(!isChatStoreReady()||!state.activeChat)return;const chatId=state.activeChat;const snap=await getDocs(query(collection(db,'chats',chatId,'messages'),limit(300)));const own=snap.docs.filter(d=>d.data().authorId===currentUid()&&!d.data().deletedForAll).reverse();await sleep(1050);for(const d of own){await updateDoc(doc(db,'chats',chatId,'messages',d.id),{text:'',type:'text',deletingForAll:false,deletedForAll:true,updatedAt:serverTimestamp()});await sleep(12)}return{cleared:own.length,total:snap.size}}
export async function deleteActiveChat(){if(!isChatStoreReady()||!state.activeChat)return;await updateDoc(doc(db,'chats',state.activeChat),{members:[],updatedAt:serverTimestamp(),deleted:true})}
export async function updateStoreReaction(messageId,reactions){if(!isChatStoreReady()||!state.activeChat||!messageId)return false;await updateDoc(doc(db,'chats',state.activeChat,'messages',messageId),{reactions:reactions||{},updatedAt:serverTimestamp()});return true}
export async function deleteStoreMessageForMe(messageId){if(!isChatStoreReady()||!state.activeChat||!messageId)return false;await updateDoc(doc(db,'chats',state.activeChat,'messages',messageId),{deletedFor:arrayUnion(currentUid()),updatedAt:serverTimestamp()});return true}
export async function deleteStoreMessageForAll(messageId){if(!isChatStoreReady()||!state.activeChat||!messageId)return false;const ref=doc(db,'chats',state.activeChat,'messages',messageId);await updateDoc(ref,{deletingForAll:true,updatedAt:serverTimestamp()});await sleep(940);await updateDoc(ref,{text:'',type:'text',deletingForAll:false,deletedForAll:true,updatedAt:serverTimestamp()});return true}
export function stopChatStore(){chatsUnsub?.();messagesUnsub?.();chatsUnsub=null;messagesUnsub=null;subscribedChatId=null;ready=false}
