import {state,activeMessages,findChat} from './state.js';import {$,esc} from './dom.js';import {appear,removeAnimated} from './animations.js';
const colorClass=c=>c==='green'?'green':c==='orange'?'style="color:#ffb054"':'red';
window.__ucmuSeenMsgIds ||= new Set();
window.__ucmuFeedRenderedOnce ||= new Set();
window.__ucmuDeletingMsgIds ||= new Set();
window.__ucmuLocallyGoneMsgIds ||= new Set();
window.__ucmuForceAppearIds ||= new Set();
export function renderAll(){renderChats();renderHeader();renderMembers();renderPrivateList();renderFeed()}
export function renderChats(){const folders=$('#folders'),list=$('#chatList');folders.innerHTML=state.folders.map(folderTpl).join('');const inFolders=new Set(state.folders.flatMap(f=>f.chatIds));list.innerHTML=state.chats.filter(c=>!inFolders.has(c.id)).map(chatTpl).join('');renderHeader()}
export function renderHeader(){const c=findChat(state.activeChat)||state.chats[0];const title=$('#chatHeadTitle'),desc=$('#chatHeadDesc'),icon=$('#chatHeadIcon');if(!title||!desc||!icon)return;title.textContent=(c?.title||'ЧАТ').toUpperCase();desc.textContent=(c?.description||c?.desc||'').toUpperCase();icon.className=(c?.id==='general'?'logo':'ava')+' chatHeadIcon';icon.style.setProperty('--chat-color',c?.styleColor||c?.color||'#d71920')}
function chatTpl(c){const style=c.styleColor||c.color||'#d71920';return `<button class="chat ${c.id===state.activeChat?'active':''} ${c.unread?'newGlow':''}" style="--chat-color:${style}" data-chat-id="${c.id}"><div class="${c.id==='general'?'logo':'ava s'}"></div><div><div class="ct">${esc(c.title)}${c.muted?'<span class="muteMark">🔕</span>':''}</div><div class="cl">${esc(c.last)}</div></div><div class="extra"><div class="time">${esc(c.time)}</div>${c.unread?`<div class="badge">${c.unread}</div>`:''}</div></button>`}
function folderTpl(f){const chats=f.chatIds.map(id=>findChat(id)).filter(Boolean);return `<div class="folder-wrap" data-folder-id="${f.id}"><button class="folder-item" style="--folder-color:${f.color||'#d71920'}"><div class="folder-icon" style="background:${f.color||'#d71920'}33">📁</div><div><div class="folder-name">${esc(f.name)}</div><div class="folder-meta">${chats.length} чатов</div></div><div class="extra">${f.open?'▾':'▸'}</div></button><div class="folder-chat-list ${f.open?'':'hidden'}">${chats.map(chatTpl).join('')}</div></div>`}
function memberDisplay(profile,uid){return profile?.displayName||profile?.username||profile?.email||(uid===state.currentUser?.uid?state.user:'User')}
function memberSub(profile,isOwner){const parts=[];if(profile?.username)parts.push('@'+profile.username);else if(profile?.email)parts.push(profile.email);if(isOwner)parts.push('владелец');return parts.join(' · ')}
export function renderMembers(){const box=$('#memberList');if(!box)return;const panel=$('#members'),title=panel?.querySelector('.ph span');const chat=findChat(state.activeChat);if(chat&&Array.isArray(chat.members)){const ids=chat.members.filter(Boolean);const profiles=chat.memberProfiles||{};const owner=chat.ownerId||chat.createdBy||ids[0];if(title)title.textContent=`УЧАСТНИКИ · ${ids.length}`;box.innerHTML=ids.map(uid=>{const p=profiles[uid]||{};const isOwner=uid===owner;return `<button class="member realMember" data-real-member-id="${esc(uid)}"><div class="ava s"></div><span><b>${esc(memberDisplay(p,uid))}</b><small>${esc(memberSub(p,isOwner))}</small></span><i class="dot"></i></button>`}).join('')||'<div class="reactionEmpty">В чате нет участников</div>';return}if(title)title.textContent='УЧАСТНИКИ';box.innerHTML='<div class="sec">Администраторы</div>'+state.people.slice(0,2).map(memberTpl).join('')+'<div class="sec">Онлайн — 5</div>'+state.people.slice(2,7).map(memberTpl).join('')+'<div class="sec">Оффлайн</div>'+state.people.slice(7).map(p=>memberTpl(p,true)).join('')}
function memberTpl(p,off=false){return `<div class="member" data-person="${esc(p)}"><div class="ava s ${off?'off':''}"></div><span>${esc(p)}</span><i class="dot ${off?'off':''}"></i></div>`}
export function renderPrivateList(){const box=$('#privateList');box.innerHTML=state.people.slice(2,6).map((p,i)=>`<div class="candidate ${i===0?'active':''}" data-person="${esc(p)}"><div class="ava s"></div><span>${esc(p)}</span><i class="radio"></i></div>`).join('')}
function prepRemoveMetrics(el){if(!el)return;const cs=getComputedStyle(el);el.style.setProperty('--ucmu-mt',cs.marginTop||'0px');el.style.setProperty('--ucmu-mb',cs.marginBottom||'14px');el.style.setProperty('--ucmu-pt',cs.paddingTop||'0px');el.style.setProperty('--ucmu-pb',cs.paddingBottom||'0px')}
export function markMessageLocallyGone(id){if(id)window.__ucmuLocallyGoneMsgIds.add(id)}
export function unmarkMessageLocallyGone(id){if(id){window.__ucmuLocallyGoneMsgIds.delete(id);window.__ucmuForceAppearIds.add(id)}}
export function renderFeed(){renderHeader();const feed=$('#feed');const chatId=state.activeChat||'none';if(window.__ucmuClearAnimatingChatId===chatId)return;let msgs=activeMessages().filter(m=>!window.__ucmuLocallyGoneMsgIds.has(m.id));const first=!window.__ucmuFeedRenderedOnce.has(chatId);const before=window.__ucmuSeenMsgIds;const newIds=[];const deletingIds=msgs.filter(m=>m.deletingForAll).map(m=>m.id);feed.innerHTML=msgs.length?msgs.map(m=>{if((!before.has(m.id)&&!first&&!m.deletingForAll)||window.__ucmuForceAppearIds.has(m.id))newIds.push(m.id);return messageTpl(m)}).join(''):`<div class="empty">У вас нет активных сообщений</div>`;msgs.forEach(m=>before.add(m.id));window.__ucmuFeedRenderedOnce.add(chatId);requestAnimationFrame(()=>{newIds.forEach(id=>{const node=feed.querySelector(`[data-msg-id="${CSS.escape(id)}"]`);appear(node);window.__ucmuForceAppearIds.delete(id)});deletingIds.forEach(id=>{if(window.__ucmuDeletingMsgIds.has(id))return;window.__ucmuDeletingMsgIds.add(id);const node=feed.querySelector(`[data-msg-id="${CSS.escape(id)}"]`);prepRemoveMetrics(node);removeAnimated(node)})});feed.scrollTop=feed.scrollHeight}
function normalizeReactions(m){if(!m.reactions)m.reactions={};if(m.reaction&&typeof m.reaction==='string'){const [emoji,countRaw]=m.reaction.trim().split(/\s+/);const n=Math.max(1,parseInt(countRaw||'1',10)||1);m.reactions[emoji] ||= [];while(m.reactions[emoji].length<n)m.reactions[emoji].push(['Leon','Jill','Chris','Alice'][m.reactions[emoji].length%4]);delete m.reaction}return m.reactions}
function shouldAnimate(m,emoji){const mark=window.__ucmuLastReact;return !!(mark&&mark.msgId===m.id&&mark.emoji===emoji&&Date.now()-mark.t<900)}
function myReactionKey(){return state.currentUser?.uid||state.user}
function reactionsTpl(m){const reactions=normalizeReactions(m);const me=myReactionKey();const chips=Object.entries(reactions).filter(([,users])=>users?.length).map(([emoji,users])=>`<button class="reactChip ${shouldAnimate(m,emoji)?'reactAppear':''} ${users.includes(me)?'mineReact':''}" data-emoji="${esc(emoji)}"><span>${esc(emoji)}</span>${users.length>1?`<b>${users.length}</b>`:''}</button>`).join('');return chips?`<div class="reactRow">${chips}</div>`:''}
function messageTpl(m){let body='';let stickerClass=m.type==='sticker'?' sticker-msg':'';let deletingClass=m.deletingForAll?' ucmu-remote-delete':'';if(m.reply)body+=`<div class="replyBox">${esc(m.reply)}</div>`;if(m.type==='sticker')body+=`<div class="sticker">${esc(m.text)}</div>`;else{body+=`<div class="txt">${esc(m.text||'')}</div>`;if(m.type==='file')body+=`<div class="file"><div class="fi">FILE</div><div><div class="file-name">${esc(m.file)}</div><div class="fs">${esc(m.size||'заглушка отправки')}</div></div><div class="dl">${m.mine?'↑':'↓'}</div></div>`;if(m.type==='photo')body+=`<div class="photo"></div>`;if(m.type==='typing')body+=`<div class="typing"><span></span><span></span><span></span></div>`}body+=reactionsTpl(m);return `<article class="msg ${m.mine?'mine':''}${stickerClass}${deletingClass}" data-msg-id="${m.id}" data-mine="${m.mine?'1':'0'}"><div class="ava s"></div><div class="bubble"><div class="meta"><span class="${colorClass(m.color)}">${esc(m.author)}</span><span class="time">${esc(m.time||'сейчас')}</span></div>${body}</div></article>`}
export function appendMessage(m){activeMessages().push(m);const feed=$('#feed');feed.insertAdjacentHTML('beforeend',messageTpl(m));const node=feed.querySelector(`[data-msg-id="${m.id}"]`);appear(node);feed.scrollTo({top:feed.scrollHeight,behavior:'smooth'})}
