import {state,activeMessages,findChat} from './state.js';import {$,esc} from './dom.js';import {appear} from './animations.js';
const colorClass=c=>c==='green'?'green':c==='orange'?'style="color:#ffb054"':'red';
export function renderAll(){renderChats();renderMembers();renderPrivateList();renderFeed()}
export function renderChats(){const folders=$('#folders'),list=$('#chatList');folders.innerHTML=state.folders.map(folderTpl).join('');const inFolders=new Set(state.folders.flatMap(f=>f.chatIds));list.innerHTML=state.chats.filter(c=>!inFolders.has(c.id)).map(chatTpl).join('')}
function chatTpl(c){const style=c.styleColor||c.color||'#d71920';return `<button class="chat ${c.id===state.activeChat?'active':''} ${c.unread?'newGlow':''}" style="--chat-color:${style}" data-chat-id="${c.id}"><div class="${c.id==='general'?'logo':'ava s'}"></div><div><div class="ct">${esc(c.title)}${c.muted?'<span class="muteMark">🔕</span>':''}</div><div class="cl">${esc(c.last)}</div></div><div class="extra"><div class="time">${esc(c.time)}</div>${c.unread?`<div class="badge">${c.unread}</div>`:''}</div></button>`}
function folderTpl(f){const chats=f.chatIds.map(id=>findChat(id)).filter(Boolean);return `<div class="folder-wrap" data-folder-id="${f.id}"><button class="folder-item" style="--folder-color:${f.color||'#d71920'}"><div class="folder-icon" style="background:${f.color||'#d71920'}33">📁</div><div><div class="folder-name">${esc(f.name)}</div><div class="folder-meta">${chats.length} чатов</div></div><div class="extra">${f.open?'▾':'▸'}</div></button><div class="folder-chat-list ${f.open?'':'hidden'}">${chats.map(chatTpl).join('')}</div></div>`}
export function renderMembers(){const box=$('#memberList');box.innerHTML='<div class="sec">Администраторы</div>'+state.people.slice(0,2).map(memberTpl).join('')+'<div class="sec">Онлайн — 5</div>'+state.people.slice(2,7).map(memberTpl).join('')+'<div class="sec">Оффлайн</div>'+state.people.slice(7).map(p=>memberTpl(p,true)).join('')}
function memberTpl(p,off=false){return `<div class="member" data-person="${esc(p)}"><div class="ava s ${off?'off':''}"></div><span>${esc(p)}</span><i class="dot ${off?'off':''}"></i></div>`}
export function renderPrivateList(){const box=$('#privateList');box.innerHTML=state.people.slice(2,6).map((p,i)=>`<div class="candidate ${i===0?'active':''}" data-person="${esc(p)}"><div class="ava s"></div><span>${esc(p)}</span><i class="radio"></i></div>`).join('')}
export function renderFeed(){const feed=$('#feed');const msgs=activeMessages();feed.innerHTML=msgs.length?msgs.map(messageTpl).join(''):`<div class="empty">У вас нет активных сообщений</div>`;feed.scrollTop=feed.scrollHeight}
function normalizeReactions(m){if(!m.reactions)m.reactions={};if(m.reaction&&typeof m.reaction==='string'){const [emoji,countRaw]=m.reaction.trim().split(/\s+/);const n=Math.max(1,parseInt(countRaw||'1',10)||1);m.reactions[emoji] ||= [];while(m.reactions[emoji].length<n)m.reactions[emoji].push(['Leon','Jill','Chris','Alice'][m.reactions[emoji].length%4]);delete m.reaction}return m.reactions}
function reactionsTpl(m){const reactions=normalizeReactions(m);const chips=Object.entries(reactions).filter(([,users])=>users?.length).map(([emoji,users])=>`<button class="reactChip reactAppear ${users.includes(state.user)?'mineReact':''}" data-emoji="${esc(emoji)}"><span>${esc(emoji)}</span>${users.length>1?`<b>${users.length}</b>`:''}</button>`).join('');return chips?`<div class="reactRow">${chips}</div>`:''}
function messageTpl(m){let body='';let stickerClass=m.type==='sticker'?' sticker-msg':'';if(m.reply)body+=`<div class="replyBox">${esc(m.reply)}</div>`;if(m.type==='sticker')body+=`<div class="sticker">${esc(m.text)}</div>`;else{body+=`<div class="txt">${esc(m.text||'')}</div>`;if(m.type==='file')body+=`<div class="file"><div class="fi">FILE</div><div><div class="file-name">${esc(m.file)}</div><div class="fs">${esc(m.size||'заглушка отправки')}</div></div><div class="dl">${m.mine?'↑':'↓'}</div></div>`;if(m.type==='photo')body+=`<div class="photo"></div>`;if(m.type==='typing')body+=`<div class="typing"><span></span><span></span><span></span></div>`}body+=reactionsTpl(m);return `<article class="msg ${m.mine?'mine':''}${stickerClass}" data-msg-id="${m.id}"><div class="ava s"></div><div class="bubble"><div class="meta"><span class="${colorClass(m.color)}">${esc(m.author)}</span><span class="time">${esc(m.time||'сейчас')}</span></div>${body}</div></article>`}
export function appendMessage(m){activeMessages().push(m);const feed=$('#feed');feed.insertAdjacentHTML('beforeend',messageTpl(m));const node=feed.querySelector(`[data-msg-id="${m.id}"]`);appear(node);feed.scrollTo({top:feed.scrollHeight,behavior:'smooth'})}
