import {stickers} from './data.js';
export function shell(){return `
<section class="auth" id="auth"><div class="auth-bg"></div><div class="auth-film"></div><div class="auth-scan"></div><div class="auth-card"><div class="logo"></div><h1>U.C.M.U. CHAT</h1><p>Secure communications</p><input id="loginName" value="Director"><input id="loginPass" type="password" value="umbrella"><button id="loginBtn">ВОЙТИ</button><button class="ghost" id="codeLogin">ВОЙТИ ПО КОДУ</button></div></section>
<main class="app" id="app">
  <aside class="side" id="side"><button class="collapse" id="collapse">‹</button><section class="profile"><div class="ava"></div><div class="info"><div class="name">Director</div><div class="online">Online</div></div></section><div class="search"><input id="sidebarSearch" placeholder="Поиск чатов"><button class="plus" id="newChat">+</button></div><div class="cap">Чаты</div><button class="folderBtn" id="folderBtn"><span>＋</span> <span class="folder-create-text">Создать папку</span></button><div class="scrollList"><div id="folders"></div><div id="chatList"></div></div></aside>
  <section class="main"><header class="head"><div class="brand"><button class="hbtn menu-btn" id="menu">☰</button><div class="logo"></div><div><h2>U.C.M.U. CHAT</h2><small>SECURE COMMUNICATIONS</small></div></div><div><div class="headerSearch" id="headerSearch"><input id="chatSearchInput" placeholder="Поиск в чате..."></div><button class="hbtn" id="searchBtn">⌕</button><button class="hbtn" id="membersBtn">♙</button><button class="hbtn" id="moreBtn">⋮</button></div></header><div class="feed" id="feed"></div><div class="drop float" id="drop"><b>Перетащите файл сюда</b><br>картинка, видео или любой файл</div><div class="stickers float hidden" id="stickers"><div class="tabs"><span>Эмодзи</span><b>Стикеры</b><span>GIF</span></div><div class="grid">${stickers.map(s=>`<button data-sticker="${s}">${s}</button>`).join('')}</div></div><footer class="compose"><button class="tool" id="attach">📎</button><textarea class="msginput" id="input" placeholder="Напишите сообщение..." rows="1"></textarea><button class="tool" id="stickerBtn">☻</button><button class="tool" id="micBtn">🎙</button><button class="send" id="send">➤</button></footer></section>
  <aside class="members float hidden" id="members"><div class="ph"><span>УЧАСТНИКИ</span><button class="close" id="closeMembers">×</button></div><input id="memberSearch" placeholder="Поиск участников"><div id="memberList"></div></aside>
  <section class="private float hidden" id="private"><div class="ph"><span>Новый личный чат</span><button class="close" id="closePrivate">×</button></div><input id="privateSearch" placeholder="Поиск по имени"><div id="privateList"></div><button class="primary" id="startPrivate">НАЧАТЬ ЧАТ</button></section>
  <input type="file" id="fileInput" hidden>
  <section class="private float hidden" id="filePreview"><div class="ph"><span>Прикрепить файл</span><button class="close" id="closeFile">×</button></div><div class="file" style="width:100%;margin:10px 0 12px"><div class="fi">FILE</div><div><div class="file-name" id="fileName">file</div><div class="fs" id="fileSize">0 MB</div></div></div><button class="primary" id="confirmFile">ОТПРАВИТЬ</button></section>
  <section class="private float hidden" id="deleteModal"><div class="ph"><span>Удалить?</span><button class="close" id="cancelDelete">×</button></div><label class="deleteAllRow"><input type="checkbox" id="deleteForAll"> Удалить для всех</label><div class="deleteHint">Если удалить только для себя, сообщение можно вернуть в течение 5 секунд.</div><button class="primary dangerPrimary" id="confirmDelete">УДАЛИТЬ</button></section>
  <div class="undoToast hidden" id="undoToast"><div class="undoText" id="undoText">Удалено для вас</div><button id="undoDelete">Вернуть</button><div class="undoBar"></div></div>
  <div class="float hidden ctx" id="ctx"><div style="display:flex;gap:9px;padding:7px 8px 10px;border-bottom:1px solid var(--line)">${['👍','🔥','✅','⚠️','🧪','☂️'].map(r=>`<button class="reactBtn" data-react="${r}">${r}</button>`).join('')}</div><button class="ctxAction" data-a="reply">↩ Ответить</button><button class="ctxAction" data-a="edit">✎ Исправить</button><button class="ctxAction" data-a="forward">↪ Переслать</button><button class="ctxAction danger" data-a="delete">🗑 Удалить</button></div>
  <div class="float hidden ctx" id="chatCtx"><button class="ctxAction chatAction" data-a="pin">📌 Закрепить</button><button class="ctxAction chatAction" data-a="mute">🔕 Выключить уведомления</button><button class="ctxAction chatAction" data-a="folder">📁 Добавить в папку</button><button class="ctxAction chatAction danger" data-a="delete">🗑 Удалить чат</button></div>
  <div class="float hidden ctx" id="folderCtx"><button class="ctxAction folderAction" data-a="pin">📌 Закрепить папку</button><button class="ctxAction folderAction" data-a="mute">🔕 Выключить уведомления</button><button class="ctxAction folderAction" data-a="style">🎨 Настроить вид</button><button class="ctxAction folderAction danger" data-a="delete">🗑 Удалить папку</button></div>
  <section class="private float hidden" id="folderModal"><div class="ph"><span>Папка чатов</span><button class="close" id="closeFolder">×</button></div><input id="folderName" placeholder="Название папки" value="Оперативные"><button class="primary" id="createFolder">СОЗДАТЬ ПАПКУ</button></section>
  <section class="private float hidden" id="folderStyleModal"><div class="ph"><span>Вид папки</span><button class="close" id="closeFolderStyle">×</button></div><input id="folderStyleName" placeholder="Название папки"><div class="folderColorRow" id="folderColors">${['#d71920','#2f7dff','#2fc46b','#d6a22c','#8b5cf6','#777'].map(c=>`<button style="width:32px;height:32px;background:${c};border:1px solid var(--line)" data-folder-color="${c}"></button>`).join('')}</div><button class="primary" id="saveFolderStyle">СОХРАНИТЬ</button></section>
</main>`}
