import {stickers} from './data.js';
export function shell(){return `
<section class="auth" id="auth">
  <div class="auth-bg"></div><div class="auth-film"></div><div class="auth-scan"></div>
  <div class="auth-stage"><div class="auth-inner" id="authInner">
    <div class="home-topbar" id="authTopbar"><div class="home-terminal">✥ U.C.M.U TERMINAL</div><div class="home-secure"><span class="orbit-indicator"></span><span>SECURE LINE</span></div></div>
    <div class="home-top-line" id="authTopLine"></div>
    <div class="home-logo" id="authLogo"><div class="home-logo-glow"></div><div class="home-logo-shine"></div><img src="assets/logo.webp" alt="U.C.M.U Logo"></div>
    <div class="home-title" id="authTitle" data-final="CHAT"></div><div class="home-subtitle" id="authSubtitle" data-final="SECURE COMMUNICATIONS"></div>
    <div class="home-holo" id="authHolo" aria-hidden="true"><div class="holo-glow"></div><div class="holo-core"></div><div class="holo-plane holo-plane-base"><i class="c1"></i><i class="c2"></i><i class="c3"></i><i class="c4"></i><b class="n1"></b><b class="n2"></b><b class="n3"></b></div><div class="holo-plane holo-plane-rise"><i class="c1"></i><i class="c2"></i><i class="c3"></i><i class="c4"></i></div></div>
    <form class="auth-form" id="authForm">
      <div class="auth-form-head"><span>IDENTITY CHECK</span><i></i></div>
      <div class="auth-tabs"><button type="button" class="auth-tab active" id="loginTab">Вход</button><button type="button" class="auth-tab" id="registerTab">Регистрация</button></div>
      <div class="rememberBox" id="rememberBox"><div class="rememberName" id="rememberName">Пользователь</div><div class="rememberUser" id="rememberUser">@username</div><div class="rememberActions"><button type="button" class="btn" id="continueBtn">ВОЙТИ</button><button type="button" class="btn2" id="switchBtn">СМЕНИТЬ</button></div></div>
      <div class="form-grid"><div class="register-only"><input class="auth-input" id="username" placeholder="@username" autocomplete="username"></div><input class="auth-input" id="email" placeholder="Email" autocomplete="email"><div class="pass-wrap"><input class="auth-input" id="password" placeholder="Пароль" type="password" autocomplete="current-password"><button class="pass-eye" type="button" data-target="password" aria-label="Показать пароль"><svg viewBox="0 0 24 24"><path d="M2 12s3.5-6 10-6 10 6 10 6-3.5 6-10 6S2 12 2 12Z"/><circle cx="12" cy="12" r="3"/></svg></button></div><div class="register-only"><input class="auth-input" id="password2" placeholder="Повтор пароля" type="password" autocomplete="off"></div><div class="register-only"><input class="auth-input" id="inviteCode" placeholder="Invite code" autocomplete="off"></div></div>
      <div class="auth-error" id="authError"></div><button class="auth-action" id="authAction">ВОЙТИ</button><div class="auth-hint" id="authHint">Firebase Auth. Доступ только для зарегистрированных пользователей.</div>
    </form>
  </div></div>
</section>
<main class="app" id="app">
  <aside class="side" id="side">
    <button class="collapse" id="collapse">‹</button>
    <section class="profile"><div class="ava"></div><div class="info"><div class="name">Director</div><div class="online">Online</div></div><button class="profileContactBtn" id="contactsBtn" title="Контакты">♙</button></section>
    <div class="search"><input id="sidebarSearch" placeholder="Поиск чатов"><button class="plus" id="newChat">+</button><button class="folderBtn iconFolderBtn" id="folderBtn" title="Создать папку">☐<span>＋</span></button></div>
    <div class="cap">Чаты</div>
    <div class="scrollList"><div id="folders"></div><div id="chatList"></div></div>
  </aside>
  <section class="main"><header class="head"><div class="brand chatHeadBrand"><button class="hbtn menu-btn" id="menu">☰</button><div class="logo chatHeadIcon" id="chatHeadIcon"></div><div><h2 id="chatHeadTitle"># ОБЩИЙ ЧАТ</h2><small id="chatHeadDesc">SECURE COMMUNICATIONS</small></div></div><div><div class="headerSearch" id="headerSearch"><input id="chatSearchInput" placeholder="Поиск в чате..."></div><button class="hbtn" id="searchBtn">⌕</button><button class="hbtn" id="membersBtn">♙</button><button class="hbtn" id="moreBtn">⋮</button></div></header><div class="feed" id="feed"></div><div class="drop float" id="drop"><b>Перетащите файл сюда</b><br>картинка, видео или любой файл</div><div class="stickers float hidden" id="stickers"><div class="tabs"><span>Эмодзи</span><b>Стикеры</b><span>GIF</span></div><div class="grid">${stickers.map(s=>`<button data-sticker="${s}">${s}</button>`).join('')}</div></div><footer class="compose"><button class="tool" id="attach">📎</button><textarea class="msginput" id="input" placeholder="Напишите сообщение..." rows="1"></textarea><button class="tool" id="stickerBtn">☻</button><button class="tool" id="micBtn">🎙</button><button class="send" id="send">➤</button></footer></section>
  <aside class="members float hidden" id="members"><div class="ph"><span>УЧАСТНИКИ</span><button class="close" id="closeMembers">×</button></div><input id="memberSearch" placeholder="Поиск участников"><div id="memberList"></div></aside>
  <section class="private float hidden" id="private"><div class="ph"><span>Новый личный чат</span><button class="close" id="closePrivate">×</button></div><input id="privateSearch" placeholder="Поиск по имени"><div id="privateList"></div><button class="primary" id="startPrivate">НАЧАТЬ ЧАТ</button></section>
  <section class="private float hidden" id="profileModal"><div class="ph"><span>Профиль</span><button class="close" id="closeProfile">×</button></div><div class="profileStub"><div class="ava"></div><div><b id="profileName">Пользователь</b><p>Профиль пока пустой</p></div></div></section>
  <section class="reactionUsers float hidden" id="reactionUsers"><div class="ph"><span id="reactionUsersTitle">Реакция</span><button class="close" id="closeReactionUsers">×</button></div><div id="reactionUsersList"></div></section>
  <input type="file" id="fileInput" hidden>
  <section class="private float hidden" id="filePreview"><div class="ph"><span>Прикрепить файл</span><button class="close" id="closeFile">×</button></div><div class="file" style="width:100%;margin:10px 0 12px"><div class="fi">FILE</div><div><div class="file-name" id="fileName">file</div><div class="fs" id="fileSize">0 MB</div></div></div><button class="primary" id="confirmFile">ОТПРАВИТЬ</button></section>
  <section class="private float hidden deleteModal" id="deleteModal"><div class="ph"><span>Удалить?</span><button class="close" id="cancelDelete">×</button></div><label class="deleteAllRow"><input type="checkbox" id="deleteForAll"> Удалить для всех</label><div class="deleteHint">Если удалить только для себя, сообщение можно вернуть в течение 5 секунд.</div><button class="primary dangerPrimary" id="confirmDelete">УДАЛИТЬ</button></section>
  <div class="undoToast hidden" id="undoToast"><div class="undoText" id="undoText">Удалено для вас</div><button id="undoDelete">Вернуть</button><div class="undoBar"></div></div>
  <div class="float hidden ctx" id="ctx"><div class="reactPicker">${['👍','🔥','✅','⚠️','🧪','☂️'].map(r=>`<button class="reactBtn" data-react="${r}">${r}</button>`).join('')}</div><button class="ctxAction" data-a="reply">↩ Ответить</button><button class="ctxAction" data-a="edit">✎ Исправить</button><button class="ctxAction" data-a="forward">↪ Переслать</button><button class="ctxAction danger" data-a="delete">🗑 Удалить</button></div>
  <div class="float hidden ctx" id="chatCtx"><button class="ctxAction chatAction" data-a="pin">📌 Закрепить</button><button class="ctxAction chatAction" data-a="mute">🔕 Выключить уведомления</button><button class="ctxAction chatAction danger" data-a="delete">🗑 Удалить чат</button></div>
  <div class="float hidden ctx" id="folderCtx"><button class="ctxAction folderAction" data-a="pin">📌 Закрепить папку</button><button class="ctxAction folderAction" data-a="mute">🔕 Выключить уведомления</button><button class="ctxAction folderAction" data-a="style">🎨 Настроить вид</button><button class="ctxAction folderAction danger" data-a="delete">🗑 Удалить папку</button></div>
  <section class="private float hidden" id="folderModal"><div class="ph"><span>Папка чатов</span><button class="close" id="closeFolder">×</button></div><input id="folderName" placeholder="Название папки" value="Оперативные"><button class="primary" id="createFolder">СОЗДАТЬ ПАПКУ</button></section>
  <section class="private float hidden" id="folderStyleModal"><div class="ph"><span>Вид папки</span><button class="close" id="closeFolderStyle">×</button></div><input id="folderStyleName" placeholder="Название папки"><div class="folderColorRow" id="folderColors">${['#d71920','#2f7dff','#2fc46b','#d6a22c','#8b5cf6','#777'].map(c=>`<button style="width:32px;height:32px;background:${c};border:1px solid var(--line)" data-folder-color="${c}"></button>`).join('')}</div><button class="primary" id="saveFolderStyle">СОХРАНИТЬ</button></section>
</main>`}
